### ISSUE TITLE
Decrediton - Responsive views

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#101]
I've already finished most of the in-app views which should be used for reference. @MariaPleshkova can cover the remaining launcher views. Included all completed views as well some of the earlier small viewport drafts for launcher. 

Referring to the master issue here, please read through before starting, as that has majority of the approach described: https://github.com/decred/decrediton/issues/1820

Key points: each view needs visual design for following viewports: 1180 px;  768 px; 375 px. 
When fitting the layout and elements into smaller views, keep the approach as much responsive and try not to introduce adaptations unless worth it. So scaling only structure, type and most elements kept the same through-out as much as possible. These smaller views are still used in desktop devices atm, thus the aim of this effort is getting a basic but visually hygenic solution on the table. Ideal mobile UI design ergonimics and sizes cannot be fully applied here.

Elements that don't fit or scale well can include simple adaptive solutions. Those need to be noted out in issues for implementation (e.g. mention of element, what's been done, how its intended to behave/function)(can check through some of the implementation issues which i've already included longer descriptions to).

**Maria: Launcher**
- [x] What’s new
- [x] Language selection
- [x] SPV selection (add desktop view from your work files)
- [x] Privacy selection
- [x] Onboarding slides
- [x] Create or Restore Wallet
- [x] - Create new wallet seeds list
- [x] - Restore existing wallet, fill seed
- [x] - Launcher overview
- [x] - Create / Restore Wallet
- [x] - Confirmation
- [x] - Advanced daemon
- [x] Logs

[decrediton - master - v017 - responsive views.xd.zip](https://github.com/decred/dcrdesign/files/2788823/decrediton.-.master.-.v017.-.responsive.views.xd.zip)

**Comment by MariaPleshkova** [comment]
XD file: [Responsive views_25.02.19.zip](https://github.com/decred/dcrdesign/files/2900840/Responsive.views_25.02.19.zip)
