### ISSUE TITLE
Events: placeholder motion graphics

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#107]
@linnutee 
- [x] .ai and .psd base template
- [x] Campus party assets

@kyleFirethought 
- [x] Motion base template
- [x] Campus party renders

@30000fps 
- [x] 2048x1024px select renders (mp4) of https://github.com/decred/dcrdesign/issues/96

**Comment by kyleFirethought** [comment]
https://drive.google.com/a/firethought.net/file/d/1l6me18omhK4iicIBwt6BsQvDu6d-n7kh/view?usp=sharing - scheduleTemplate(beta)

There is further js elements to be added in the future that should remove a few unecesary clicks.  This will be amended for a future event. 

Testing welcome!

- Kyle
