### ISSUE TITLE
Politeia Digest graphic

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdesign#113]
I liked the graphic that was made previously for pi digest and would be happy to continue using it, but I don't think having the month in the graphic is great because most of the issues don't cover a full month. It is more common for an issue to cover a week or two.

When I decide that there is enough action to warrant an issue, I take a snapshot and then try to have the final version published within 12-24 hours. I feel it is important that pi digest has this short turnaround time so that reported information is "live" at time of publication.

It does not seem reasonable to expect other people to respond with updated graphics on this kind of timeframe, so I don't think having the specific dates in the image will work unless I can add them myself.

Here are a few options for how this could be approached (I am happy with any):
1. One graphic that has no month, so could be same as the December one without "December 2018", and I re-use it each time.
2. A number of month-less graphics that I cycle through.
3. We figure out a way that I can add the dates to a pre-prepared image without mangling it. I use the format "Issue 9- Dec 12-Dec 31 2018". I have Gimp but I am not at all skilled in using it.

To reiterate, I like the image that was made for December and would be happy to use that (without the month line), anything more is a bonus.

**Comment by 30000fps** [comment]
![politeia-digest_january2019_2048x1024](https://user-images.githubusercontent.com/15022929/52489862-9fbb9a80-2bc3-11e9-8b27-8857cd0721b1.png)

**Comment by 30000fps** [comment]
![politeia-digest_2048x1024_v3](https://user-images.githubusercontent.com/15022929/52491664-e3b09e80-2bc7-11e9-89d3-fcad7c295dec.png)
![politeia-digest_2048x1024_v4](https://user-images.githubusercontent.com/15022929/52491666-e4493500-2bc7-11e9-9497-a17737992f45.png)

**Comment by linnutee** [comment]
Included the xd template here. The digest releases can go through the set of these pre-made renders. When these run out, can make an issue for an additional larger set to be cycled through. 

@30000fps can include the previous 2048x1024px from https://github.com/decred/dcrdesign/issues/90 w/o any data on it here as well. 

[decred  - pi digest - templates.xd.zip](https://github.com/decred/dcrdesign/files/2851728/decred.-.pi.digest.-.templates.xd.zip)

**Comment by RichardRed0x** [comment]
@linnutee @30000fps I have used the first template now, thanks,
Not sure where to ask for the template version of the other images.
