### ISSUE TITLE
Request: Decred SF meetup cover illustration

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#118]
Forwarding a request from Max Bronstein: graphic for our meetup page: https://www.meetup.com/San-Francisco-Decred-Meetup/

E.g. Golden Gate bridge in DCR signature illustration style, incorporate DCR symbol in the image. 

Size and use references
https://help.meetup.com/hc/en-us/articles/360002860712-How-do-I-set-my-Meetup-group-s-cover-photo-
https://www.meetup.com/find/tech/

**Comment by koosake** [comment]
![sfmeetup_dcr](https://user-images.githubusercontent.com/39430283/53438971-b2c6cb00-3a09-11e9-8bf4-975ad87290f8.png)
The illustration

**Comment by koosake** [comment]
Link to .svg - https://www.dropbox.com/s/sw52d83uaw8014y/SFmeetup_dcr.svg?dl=0

**Comment by linnutee** [comment]
Cheers. Noting that post above by koosake is 1200x676px standard for the meetup.com https://www.meetup.com/San-Francisco-Decred-Meetup/ page header. That one can only contain the Decred symbol, as in different instances, Decred name with the group name will be overlayed ontop of the lower part of the image in meetup.com UI.

This one below is for a twitter announcement post, 2048px. 
![dcr - twitter - sf meetup - 2048px](https://user-images.githubusercontent.com/17774057/53439769-962b9280-3a0b-11e9-8431-72109c5220ae.png)

**Comment by Dustorf** [comment]
That's a beautiful illustration, thank you!

**Comment by Dustorf** [comment]
@koosake could you amend the image to reflect a joint event with OKCoin? I would like that tomorrow
 if possible

**Comment by maxbron08** [comment]
This is awesome, thanks so much for this!

**Comment by jzbz** [comment]
Please don't use the image until it's fixed. "San Francisco" is misspelled.

**Comment by koosake** [comment]
![sfmeetup_dcr_ok](https://user-images.githubusercontent.com/39430283/53484234-0843bc00-3a8c-11e9-97f1-e417a3d5ae10.png)
Added okcoin logo and heres the .svg
https://www.dropbox.com/s/rj0hqlvxjfei63y/SFmeetup_dcr_ok.svg?dl=0

**Comment by linnutee** [comment]
Deleted last post, as the Okcoin one turned out to be for another event, not related to this.
