### ISSUE TITLE
Decred in Depth - Podcast visuals/concept

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#119]
Micro-identity for promotion of the new Decred in Depth podcast. 

- [x] Concept design
- [x] Visual assets
- [x] Motion assets
- [x] Twitter motion template
- [x] Spotify key visual
- [x] iTunes key visual

**Comment by linnutee** [comment]
Key Visuals for Spotify and iTunes (3000px square) [decred - in depth - intunes and spotify cover.zip](https://github.com/decred/dcrdesign/files/2919678/decred.-.in.depth.-.intunes.and.spotify.cover.zip). Kudos to @30000fps for motion and key visual renders. 

Overall approach: 
- Spotify and iTunes use a single static cover visual for the podcast as whole. Afaik there are no episode specific visuals in Spotify and ones in iTunes are fairly unused so those are not included (can be in the future if found needed). 

- Twitter promotion is episode specific and built as a motion template to allow for quick creation of episode renders. Textual content overlays are based on the common DCR templates; motion background is derived from the podcasts key visual. Overall idea is to display a slow pan-out of an abstracted DCR symbol form (illustrating the "in depth" title through motion), whereas the stroke elements that make it up function as an audio spectrum visualizer synced with the podcasts audio. @kyleFirethought and @marcelolustosa are working with the template to produce each episodes renders. 

![screenshot 2019-03-01 at 16 19 18](https://user-images.githubusercontent.com/17774057/53644185-a7101a00-3c3e-11e9-84ab-e417c9b1a3b5.png)


<img width="1708" alt="screenshot 2019-03-01 at 16 05 06" src="https://user-images.githubusercontent.com/17774057/53643798-a5922200-3c3d-11e9-8dfc-29dba17ef376.png">

**Comment by kyleFirethought** [comment]
Link to project files, example and mogrt files: https://drive.google.com/a/firethought.net/file/d/1436HCBGnAM5lJ2aIRoHhRDwFnHCW_ZZr/view?usp=sharing
