### ISSUE TITLE
Politeia Digest - Medium banner

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdesign#121]
On Medium publications have a wide logo which appears at the top of every story page:

> This logo appears at the top of all your publication’s stories. It should have a transparent background, and be at least 600px wide and 72px tall.

I don't have anything that's usable for this. The Decred account has a fairly plain blue one (see top of [example post](https://medium.com/decred/decred-journal-january-2019-358943759f79)). If it was possible to produce something simple that I could use it would be much appreciated.

**Comment by linnutee** [comment]
@saender can give another opinion on this when back in a week, as he's done the whole social media batch earlier. As far as I remember, it likely was the case for Medium that the solid color background was the most optimal approach. The ultra wide / short strips had some scaling issues and a larger two image setting is superfluous. 

The image scaling for these ultra-wide variants

**Comment by saender** [comment]
@RichardRed0x If You need to make Pi Digest header then use Pi key colors and horizontal/wide logo lock-up. Also ask dcr medium admin to know what knobs to tweak/substitude.

Color selection:
Recommended bg color: #f9fafa
https://github.com/decred/dcrdesign/issues/81

Logo selection:
Recommended logo: transparent background - primary - positive - gradient
https://github.com/decred/dcrdesign/issues/83

An if You can then menu text color next to logo: #3d5873

Preview w recommended selection (would align well w future Politeia UI):
<img width="937" alt="Screen Shot 2019-03-22 at 21 05 08" src="https://user-images.githubusercontent.com/29069168/54847143-42e4f100-4ce6-11e9-8e61-e848b4e0620f.png">

And let me know regarding the upmentioned if needed.

**Comment by RichardRed0x** [comment]
I'm afraid I don't follow the instructions @saender, not sure what they mean. The graphic in your comment looks good though.
Yes that's the right account @linnutee

**Comment by linnutee** [comment]
I think what Sander meant, there's a set of options within Mediums admin UI to produce this kind of minimal layout as described. As this is the same as on Decred's profile. Anyone who has admin access to Decred one should be able to take a screenshot of what the exact options are and you can duplicate those on Pi journal. Just need to change the colour values.
