### ISSUE TITLE
DA mogrt and previous assets

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#122]
- [x] DA Theme
- [x] Mogrt Assets
- [x] Design Templates

Elements required by Dustin re: Reboot.

**Comment by kyleFirethought** [comment]
[DA.-.Mogrt.zip](https://github.com/decred/dcrdesign/files/2972946/DA.-.Mogrt.zip)

**Comment by kyleFirethought** [comment]
[DA.-.Theme.zip](https://github.com/decred/dcrdesign/files/2972948/DA.-.Theme.zip)

**Comment by linnutee** [comment]
@koosake ; @marcelolustosa did a small update to the assembly Twitter images by aligning those with the common series overlay as used by other series. [dcr - assembly - graphics.zip](https://github.com/decred/dcrdesign/files/3004912/dcr.-.assembly.-.graphics.zip)

<img width="1769" alt="Screenshot 2019-03-25 at 20 22 28" src="https://user-images.githubusercontent.com/17774057/54944257-c6e3e680-4f3b-11e9-8992-049e9a4bb960.png">

Guidelines and reference to photo treatment:
![dcr - assembly - guidelines](https://user-images.githubusercontent.com/17774057/54944184-98660b80-4f3b-11e9-9e29-03529702f38a.png)
<img width="2077" alt="dcr - image treatment - reference" src="https://user-images.githubusercontent.com/17774057/54944191-9a2fcf00-4f3b-11e9-81dc-eb0e68362beb.png">
