### ISSUE TITLE
Need graphic for Luke Powell at SF Decred Devs Meetup

### ISSUE THREAD

**Issue by maxbron08** [decred/dcrdesign#124]
We're hosting our second SF Decred Devs Meetup and a new banner image for the meetup would be awesome. I was thinking something along the lines of the [original](https://www.meetup.com/San-Francisco-Decred-Meetup/) but with Luke's caricature. The title will be 'Coordinating Open Source: Today and Tomorrow.'

Feel free to reach out on matrix @max_bronstein if there are any other specific questions

**Comment by linnutee** [comment]
Mentioning that the group banner was intended as a static one for longer use. 

So this one would be an event specific image – used at the meetup.com event subpage as well twitter. Can stick with the common event/talk structural template.

**Comment by maxbron08** [comment]
Yes! that would be awesome. Let's stick with the common template. We'll likely use the group banner for future posts, but this one will be hosted at Coinbase so we want the production value to be good.

**Comment by maxbron08** [comment]
Would be great to get this turned around today so we can announce it Thursday morning.

**Comment by marcelolustosa** [comment]
hi Max, sent you some questions on matrix

**Comment by marcelolustosa** [comment]
![dcr---conference---template](https://user-images.githubusercontent.com/39598223/55164696-e3a23900-514a-11e9-83bf-53ff4d0db489.png)

That would be for meetup.com event page. Need event details (date, time and place) for the twitter version

**Comment by maxbron08** [comment]
This is awesome, thanks!
