### ISSUE TITLE
Decred in Depth: Template updates

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#127]
Few additions: 

- [x] Soundcloud header and profile pic
- [x] Add soundcloud icon to motion templates

**Comment by linnutee** [comment]
Updated the last slide of the template, added soundcloud icon and copy as well inverted the icon colors to stand out better against the bg. 

Template .ai: [dcr - in depth podcast - spotify and twitter template - v002.ai.zip](https://github.com/decred/dcrdesign/files/3048874/dcr.-.in.depth.podcast.-.spotify.and.twitter.template.-.v002.ai.zip)
SC profile and cover: [decred in depth - sc profile and cover.zip](https://github.com/decred/dcrdesign/files/3048883/decred.in.depth.-.sc.profile.and.cover.zip)

<img width="1705" alt="Screenshot 2019-04-05 at 19 47 07" src="https://user-images.githubusercontent.com/17774057/55643435-c836ce00-57db-11e9-94d8-ced0942d930c.png">

<img width="1101" alt="Screenshot 2019-04-05 at 19 43 27" src="https://user-images.githubusercontent.com/17774057/55643445-cff67280-57db-11e9-89c3-40d9de2975f5.png">

**Comment by kyleFirethought** [comment]
Updated the Motion Template file with the Soundcloud icon and additional text.
[decredPodcastMogrts.zip](https://github.com/decred/dcrdesign/files/3051758/decredPodcastMogrts.zip)
