### ISSUE TITLE
Stakepool theme: responsive and mobile views

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#13]

**Comment by MariaPleshkova** [comment]
**Tablet version**
Main screens for a tablet view

- [x] Login/Register+examples of fields states
- [ ] Home page(visitor)
- [x] Stats page(visitor)
- [x] Connect page+pop up
- [x] Voting page
- [x] Admin view_low fee tickets page
- [x] Admin view_status page

**Comment by MariaPleshkova** [comment]
**Mobile version**
Main screens for a mobile view

- [x] Login/Register+examples of fields states
- [ ] Home page(visitor)
- [x] Stats page(visitor)
- [x] Connect page+pop up
- [x] Voting page
