### ISSUE TITLE
dcrtimegui UI/UX improvements

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#131]
Maria/Vlad: 

- Should look at the both possible users flows of adding new files and looking up existing digests (e.g. search in navigation or adding the digests page/section where a search is present?). The latter would allow for an interaction to enter an existing digest and direct the user to results page and either display results or also have an empty state (if no match).
- Navigation back and forth the results can be refined a bit (guess this depends on how the look-up or "search digest" is designed).
- The type and description details maybe could be refined a tad bit, consider use of some icons and improving the typesetting. By this I don't mean anything blingy obviously but still keeping things clear, simple and straight-forward. If need of additional icons for some metaphor, can request from @koosake – she's recently been updating the icon package. 
- File-drop and followed details + upload button should be improved visually.
- Loading page can also be improved, e.g. use of some existing motion assets from decrediton. (i'm unable to screenshot this as it seems to load extremely fast). 
Also please read: https://github.com/decred/authit/issues/42 & https://github.com/decred/authit/issues/59

All implementation issues post to: https://github.com/decred/authit

<img width="1919" alt="Screenshot 2019-04-03 at 17 23 28" src="https://user-images.githubusercontent.com/17774057/55496994-f6d06f80-5648-11e9-8116-df51211c8ae1.png">
<img width="1919" alt="Screenshot 2019-04-03 at 17 23 42" src="https://user-images.githubusercontent.com/17774057/55496993-f6d06f80-5648-11e9-9189-29121c4b2c65.png">
<img width="1919" alt="Screenshot 2019-04-03 at 17 23 43" src="https://user-images.githubusercontent.com/17774057/55496992-f6d06f80-5648-11e9-9eeb-dc5577f4f7d0.png">
<img width="1919" alt="Screenshot 2019-04-03 at 17 23 10" src="https://user-images.githubusercontent.com/17774057/55496995-f6d06f80-5648-11e9-9fb4-782815adfa95.png">

**Comment by linnutee** [comment]
Included derivate logo for the service. 

<img width="998" alt="Screenshot 2019-04-03 at 19 54 02" src="https://user-images.githubusercontent.com/17774057/55497540-3fd4f380-564a-11e9-97f3-eeb60c51fd90.png">

[dcr - derivate logo - timestamp service.svg.zip](https://github.com/decred/dcrdesign/files/3039841/dcr.-.derivate.logo.-.timestamp.service.svg.zip)

**Comment by harlovski** [comment]
XD file: [Timestamp.zip](https://github.com/decred/dcrdesign/files/3138482/Timestamp.zip)
https://github.com/decred/dcrtimegui/issues/67
