### ISSUE TITLE
Politeia Digest, more header images?

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdesign#134]
I have used the 4 images produced by @30000fps in issue #113 now. Could I have some more please?

**Comment by 30000fps** [comment]
![Politeia-Digest_2048x1024_R2 1](https://user-images.githubusercontent.com/15022929/55898724-7fa85780-5bc3-11e9-8e7c-9cb74c6cbc7c.png)
![Politeia-Digest_2048x1024_R2 2](https://user-images.githubusercontent.com/15022929/55898725-7fa85780-5bc3-11e9-8dee-50a147f4d31d.png)
![Politeia-Digest_2048x1024_R2 3](https://user-images.githubusercontent.com/15022929/55898726-7fa85780-5bc3-11e9-8576-bf83723e88cd.png)
![Politeia-Digest_2048x1024_R2 4](https://user-images.githubusercontent.com/15022929/55898727-7fa85780-5bc3-11e9-94a7-0fcab0e1e821.png)
![Politeia-Digest_2048x1024_R2 5](https://user-images.githubusercontent.com/15022929/55898728-8040ee00-5bc3-11e9-904c-9a5132a535ec.png)
![Politeia-Digest_2048x1024_R2 6](https://user-images.githubusercontent.com/15022929/55898729-8040ee00-5bc3-11e9-9f65-4ec220afce56.png)

**Comment by RichardRed0x** [comment]
Looking good, thanks. Do I need different aspect ratios for different social media platforms? I've been using the twitter and medium sized images so far, don't touch facebook.

**Comment by 30000fps** [comment]
Good question – I'm not sure if FB images require a different aspect ratio. If you find out that you need variations in scale let me know and I can create the other versions for you.

**Comment by linnutee** [comment]
This size should be fine actually. Afaik FB was smaller than twitter, so these can be just cropped in the xd template. 

We'll get the other templates sorted into xd as one batch in near future, will add one for Pi journal fb also. Meanwhile can just use the twitter one in fb also, as its just a finer detail to get the absolute right proportion for each platform.
