### ISSUE TITLE
Need an image for Insaf NORI at IEEE Morocco Blockchain Summit

### ISSUE THREAD

**Issue by Insaf01** [decred/dcrdesign#135]
We'll be participating with a booth on IEEE Morocco Blockchain Summit that will be held on the 24 and the 25th of April. The title will be "Join Decred at the First Morocco Blockchain Summit", and as of the placa of the event it will be at : INPT, Rabat, Morocco.

This is the link to the event: [IEEE Morocco Blockchain Summit](http://blockchainsummit.ma/#home)

Feel free to reach out to me on matrix @arij:decred.org if you have any question

**Comment by linnutee** [comment]
@Insaf01 got a twitter image ready for this. Download below: 

![dcr - twitter - morocco summit - 2048px](https://user-images.githubusercontent.com/17774057/55832333-04409a80-5b1e-11e9-928d-e192e3a2e65f.png)

**Comment by Insaf01** [comment]
Thanks @linnutee , that's a good one!
