### ISSUE TITLE
Images for Decred participation in Talent Land and CriptoLatinFest

### ISSUE THREAD

**Issue by 3lian** [decred/dcrdesign#137]
Hi, I'm rising this issue to ask you for three images that will be used during Talent Land in Mexico and CriptoLatinFest in Colombia. 

First image: Elian Huesca presents "Re-Imagina el Dinero Digital: Fundamentales sobre Decred", Miércoles 24 de Abril, 13:00hrs, Blockchain Land, Guadalajara, Mexico. 

Second image: Elian Huesca presents "Decred a profundidad: Decrediton, Politeia y cómo desarrollar con nosotros", Jueves 25 de Abril, 17:00hrs, Blockchain Land, Guadalajara, Mexico.

I found the following logos of Talent Land (https://www.talent-land.mx/): 

![talentland1](https://user-images.githubusercontent.com/26446555/56174244-3e46ec00-5fb7-11e9-889b-0d27c519b361.png)
![talentland2](https://user-images.githubusercontent.com/26446555/56174245-3e46ec00-5fb7-11e9-8b2e-fda93fddbce5.png)
  
Third image: Elian Huesca presents " Decred en 20 minutos", Sábado 18 de Mayo, 14:00hrs, Bogota, Colombia. 

I found the following Logo for CriptoLatinFest (https://criptolatinfest.com/):

![criptolatinfest](https://user-images.githubusercontent.com/26446555/56174257-4c950800-5fb7-11e9-814a-cd665301269a.png)

![criptolatinfest1](https://user-images.githubusercontent.com/26446555/56174395-e8267880-5fb7-11e9-8cb3-c5967e07d453.png)

Please let me know if there is any other detail you may need. Thanks and best regards!

**Comment by 3lian** [comment]
![LOGO_criptolatinfest_CURVAS (1)-01](https://user-images.githubusercontent.com/26446555/56174876-4eac9600-5fba-11e9-9cdc-73fc80e9ec3f.png)
![logo_cripto](https://user-images.githubusercontent.com/26446555/56174877-4eac9600-5fba-11e9-99b9-973144410800.png)
![logo blanco-01](https://user-images.githubusercontent.com/26446555/56174878-4eac9600-5fba-11e9-8538-241bfe016a7a.png)

**Comment by marcelolustosa** [comment]
Hi Elian,
We have a template for conferences where we have multiple speakers or/and a booth. 

Used it for Talent Land, and the regular one for Criptofest, as it follows:

![cryptofest](https://user-images.githubusercontent.com/39598223/56315671-ae2bb280-612e-11e9-8fc6-5cbedd61f584.png)
![talentland](https://user-images.githubusercontent.com/39598223/56315672-ae2bb280-612e-11e9-8315-34409d00e279.png)

**Comment by 3lian** [comment]
Thanks @marcelolustosa !!! I'll be sharing on social media, cheers!
