### ISSUE TITLE
Decred x EXMO integration image

### ISSUE THREAD

**Issue by denyszayets** [decred/dcrdesign#140]
We need an image that represents DECRED + [EXMO](https://exmo.com/en/) exchange integration to use on social media. In the next week or so, EXMO team will be adding Decred to their platform with a particular focus on Eastern Europe and the Russian speaking population.

- DCR/BTC
- DCR/RUB 
- DCR/UAH

Logo EXMO
[exmo logos.zip](https://github.com/decred/dcrdesign/files/3127652/exmo.logos.zip)

Adding @jzbz here since this will be going on main twitter account too.
Thanks

**Comment by denyszayets** [comment]
![moscow-kremlin-P7Y8LH3](https://user-images.githubusercontent.com/33739891/56905211-cb854880-6a6d-11e9-8ac4-b73c0f8fda1c.jpg)
background suggestion

**Comment by Decommission** [comment]
I had a call with linnutee today. I'll create some initial propositions based on our existing templates framework

**Comment by Decommission** [comment]
![140-exmo-v1](https://user-images.githubusercontent.com/50079053/57575067-0d39ca00-7444-11e9-95dd-25e882bcefc0.jpg)
Here is my first proposal with some abstract patterns. How do you like it?

**Comment by denyszayets** [comment]
Thanks! Tanel approved in Matrix

DENYS ZAYETS Cryptobits Tech, LLC. - UI/UX Graphic Designer
(904) 613-5591 denyszayets.com [http://denyszayets.com/] & @denyszayets [https://twitter.com/denyszayets]
On Sat, May 11, 2019 at 17:30, mission <notifications@github.com> wrote:
[https://user-images.githubusercontent.com/50079053/57575067-0d39ca00-7444-11e9-95dd-25e882bcefc0.jpg]
Here is my first proposal with some abstract patterns. How do you like it?
