### ISSUE TITLE
"Decred Journal" april issue images

### ISSUE THREAD

**Issue by saender** [decred/dcrdesign#143]
Images for GH, Twitter, Medium and Facebook release.

Preview:
<img width="954" src="https://user-images.githubusercontent.com/29069168/56983970-9ff97f80-6b8d-11e9-8707-4bb89924257e.png">

Package:
["Decred Journal" april image package.zip](https://github.com/decred/dcrdesign/files/3132581/Decred.Journal.april.image.package.zip)

**Comment by xaur** [comment]
@saender what is the theme of April image?
