### ISSUE TITLE
Decred Washington DC Event Image

### ISSUE THREAD

**Issue by nottrunner** [decred/dcrdesign#146]
Similar to SF an image for our kickoff.  This event is being co-sponsored by the Dartmouth Entrepreneurial Network of DC.   Perhaps the DEN logo can be incorporated as well [dendc.org](url)

![image](https://user-images.githubusercontent.com/17677506/57232438-94251780-6fea-11e9-90c9-704704ec11b8.png)

**Comment by marcelolustosa** [comment]
![dcr_-_washington_twitter](https://user-images.githubusercontent.com/39598223/57328108-e8152680-70e6-11e9-8a48-1813d4636234.png)

**Comment by nottrunner** [comment]
Perfect. Thanks
