### ISSUE TITLE
Images for Decred participation in La Conexión, BitcoinDay Uy and Blockchain Summit Latam 

### ISSUE THREAD

**Issue by 3lian** [decred/dcrdesign#147]
Hi, I'm rising this issue to ask for two images for Decred's participation in events in Latam:

1- "La Conexión" to be held on May 20 and 21 in Medellin, Colombia, I'm presenting "Decred en 20 minutos", about the details of the event: May 20 & 21, Country Club Ejecutivos, Medellín, Colombia. 
![La_Conexion2](https://user-images.githubusercontent.com/26446555/57390464-05e39980-7182-11e9-96cf-608b6f65aa2d.png)

2- "BitcoinDay UY" to be held on May 23 and 24 in Montevideo, Uruguay, I'm presenting "Decred en 20 minutos", about the details of the event: May 23 & 24, Auditorio Antel, Montevideo, Uruguay. 
![Logo_bitcoinday_iso_logo_UY](https://user-images.githubusercontent.com/26446555/57390576-53600680-7182-11e9-8cc5-800e4c1733ec.png)

Please let me know if you have any doubts of comments. Thank you in advance!

**Comment by marcelolustosa** [comment]
Hi Elian,

It would be nice to have those logos in a vector format (svg, ai or any other). For Montevideo event I can work with their social media pictures, but Medellin one will be very hard to work with the bitmaps they provide in their media channels

**Comment by marcelolustosa** [comment]
![colombia](https://user-images.githubusercontent.com/39598223/57638534-5729c980-7584-11e9-92c4-908043bf6338.png)
![uruguay](https://user-images.githubusercontent.com/39598223/57638536-57c26000-7584-11e9-826c-4d5f1ee24410.png)
