### ISSUE TITLE
Lagos Event Image 

### ISSUE THREAD

**Issue by nottrunner** [decred/dcrdesign#148]
Graphic similar to SF and DC meetup images. This could be the backdrop 
![A9B17BDC-DFE5-45A8-BF60-BBD7125F311F](https://user-images.githubusercontent.com/17677506/57491998-1fbdd300-728d-11e9-9b5d-0c848774ae2f.png)

**Comment by nottrunner** [comment]
Blockchain, AI, and Digital Assets Conference
The Civic Centre
Ozumba Mbadiwe Road,  Victoria Island 
Lagos, Nigeria

**Comment by linnutee** [comment]
I'll mention regarding this – the custom illustrations go only for headers which are used for longer time. Single event promo images generally are kept quick and simple in production. 

This photo is alright for a background if gone through treatment, however do provide a confirmation that it also has free use rights.

**Comment by nottrunner** [comment]
It’s safe to use the image especially sue we are going to further transform it.

**Comment by nottrunner** [comment]
We just need the basic treatment similar to DC and SF as stated.

**Comment by marcelolustosa** [comment]
![lagos](https://user-images.githubusercontent.com/39598223/57638444-2e093900-7584-11e9-9890-7bb6e2a9f1d2.png)

Had to look for a Lekki Ikoyi bridge photo with modification rights

**Comment by nottrunner** [comment]
Thanks it’s perfect

**Comment by nottrunner** [comment]
Can you also send the same image with only the decred logo, no text

**Comment by nottrunner** [comment]
And no event logo

**Comment by marcelolustosa** [comment]
Sure I can!

Can you tell me where you using it? I may be able to save you a more appropriated file, accordingly to the usage you need.

**Comment by nottrunner** [comment]
Basic banners, print material, booth backdrops etc.
I guess we can just canvass the standard repository of  images that already exist?

**Comment by marcelolustosa** [comment]
We have standard print materials here: https://www.notion.so/Decred-Print-Matter-2768d31b683a450393e19b90f17c02e1
There's also a default booth design: https://github.com/decred/dcrdesign/issues/116#issuecomment-477246331

I can customize it to your needs, just provide booth and/or banners dimensions

**Comment by nottrunner** [comment]
Thanks. The guys on the ground sorted material needs out. 

Thanks for all the great work man, thanks for coming through.
