### ISSUE TITLE
wording of dcr features handout card

### ISSUE THREAD

**Issue by raedah** [decred/dcrdesign#149]
Looking at the materials on 
https://github.com/decred/dcrdesign/releases
Handouts/Cards/pdf/'dcr - features - A6+3.pdf', 

This shows the following text
"The Development on Decred is focussed on the production of open-source infrastructure in general, and on decentralization and governance in particular."

I recall a discussion on chat many months back that this wording was found inadequate so I was surprised to still see it in the print materials. The use of "in general" and "in particular" is ambiguous and confusing. Can also note that there is no reason to capitalize Development in a sentence, and focused can be spelled with a single s. Opening this issue to gather community feedback and get to the bottom of it.

![postcard](https://user-images.githubusercontent.com/15878246/57561660-879f1700-737c-11e9-848a-21537720fcdd.png)

**Comment by s-ben** [comment]
Perhaps we can use Ditto's "foundational messaging" they came up with a couple months ago?
https://pastebin.com/E5L6u2RV

**Comment by nottrunner** [comment]
That’s a good idea. I’m in support.

**Comment by s-ben** [comment]
The two options that make the most sense to me just from glancing at the messaging doc (below). I suppose it depends on the purpose of this specific card.

**WHAT IS DECRED?**
Decred is a community-directed digital currency designed to be a superior store of value for generations to come.
* Its hybrid PoW+PoS consensus mechanism, transparent proposal and voting system, and continually funded treasury, make it secure, adaptable, and self-sustaining.
* Decred stakeholders collectively determine the policy, development plan, budget, changes to the consensus rules, and they approve the miners’ work.
* Each block reward compensates miners, stakeholders, and the project Treasury (that pays contractors who work on Decred).

OR 

**Mainstream Audience**
Decred is a community-directed digital currency designed to deliver a truly decentralized alternative to traditional money. In the current system, a centralized authority such as a bank or government holds the power. With Decred, the community members own and operate the system, make the rules, and determine the direction of the project. The result is a secure and adaptable currency that is a superior store of value. Everyone is invested and actively involved in helping Decred succeed.

**Comment by linnutee** [comment]
Referring to this open copywriting issue here: https://github.com/decred/dcrdesign/issues/60

Perhaps @Dustorf can pitch in here. I'd take the foundational messaging rather as guidance / tool and refine a more elaborate and concrete copy blurbs for the print materials. Also rough consensus has been to reduce the amount of print collateral?
