### ISSUE TITLE
Decred Canada Meetup cover illustration

### ISSUE THREAD

**Issue by Michae2xl** [decred/dcrdesign#150]
To - https://www.meetup.com/DecredCanada/

Similar to the DC / SF image.

Thank you so much!

**Comment by Michae2xl** [comment]
Hello 👋

**Comment by marcelolustosa** [comment]
messaged you about it on May, 22 ;)

**Comment by Michae2xl** [comment]
where? Matrix?

**Comment by marcelolustosa** [comment]
working on it

**Comment by linnutee** [comment]
I assume this got solved or dropped. If solved @marcelolustosa do post result for archiving.

**Comment by Michae2xl** [comment]
It was not solved.
