### ISSUE TITLE
Decred BlueYard meetup image

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdesign#151]
Need something to tweet for this event:
https://www.eventbrite.co.uk/e/decred-x-blueyard-berlin-meetup-tickets-61631192556

**Comment by marcelolustosa** [comment]
![dcr_social_media_blue_yard](https://user-images.githubusercontent.com/39598223/58197399-8c2fcd80-7ca2-11e9-8861-3b6a45cfd137.png)
