### ISSUE TITLE
Images for Decred participation in Blockchain Summit Latam 

### ISSUE THREAD

**Issue by 3lian** [decred/dcrdesign#156]
Hi, I'm rising this issue for an image for our participation in Blockchain Summit Latam https://www.blockchainsummit.la 

Details of the event:
**Join Decred at Blockchain Summit Latam**
Crowne Plaza Hotel, 
Dakota 95, Nápoles, CDMX
4 y 5 de Julio de 2019 

Here are the logos of Blockchain Summit Latam 
https://drive.google.com/file/d/10JA6vpudoAauXgvzMDpRAomJgS5FtRAl/view
https://drive.google.com/file/d/1Qk1pWboH2F8n5kUpdyjHY5c4ubck4ap6/view

Posible using a very Mexican symbol as the Independence Angel as background: https://duckduckgo.com/?q=angel+de+la+independencia&t=brave&iax=images&ia=images&iai=https%3A%2F%2Fwww.eleconomista.com.mx%2F__export%2F1546470902919%2Fsites%2Feleconomista%2Fimg%2F2019%2F01%2F02%2Fangel-de-la-independencia-shutterstock.jpg_423392900.jpg

Past example: https://twitter.com/Decred_ES/status/1118723481481486336 

Let me know if you have any comments or doubts. Thanks in advance! 

Best!

**Comment by 3lian** [comment]
Hi design team, any news on this piece? Thanks in advance!

**Comment by 3lian** [comment]
Hello design team, just a kind reminder that Blockchain Summit Latam is next weekend. Looking forward to your comments. Best regards and thanks in advance.

**Comment by marcelolustosa** [comment]
![summit](https://user-images.githubusercontent.com/39598223/60367108-c5570e00-99c3-11e9-8213-73ca8fc5d675.png)

Sorry for the delay. Their logotype is not optimal - always try to get vector logotypes (svg, pdf, ai).
Posting as it is due to the deadline.

Thanks Elian!

**Comment by 3lian** [comment]
Fantastic @marcelolustosa !! Thanks for the design, looks great!! I'm closing this issue. Best regards!
