### ISSUE TITLE
Contributors portraits Jun 2019

### ISSUE THREAD

**Issue by marcelolustosa** [decred/dcrdesign#157]
Akin Sawyer:
[Akin.zip](https://github.com/decred/dcrdesign/files/3282130/Akin.zip)

**Comment by linnutee** [comment]
@marcelolustosa Could you make an issue to dcrweb also (include the previous round in case they weren't) and tag jz to provide the info. E.g. https://github.com/decred/dcrweb/issues/632

**Comment by marcelolustosa** [comment]
done: https://github.com/decred/dcrweb/issues/679
