### ISSUE TITLE
Graphic for SF Decred Meetup with Coinbase Custody

### ISSUE THREAD

**Issue by maxbron08** [decred/dcrdesign#158]
We're hosting a Happy Hour for the SF Decred Meetup alongside our sponsors, Coinbase Custody on June 26th. We'd love a graphic to put on the meetup page: https://www.meetup.com/San-Francisco-Decred-Meetup/

The previous graphic we had for the last even was great, we want to similarly have the Coinbase Custody logo in the graphic: https://www.meetup.com/San-Francisco-Decred-Meetup/events/260046546/

**Comment by marcelolustosa** [comment]
Do you have more info on the event? Like time and date, speakers (if any), like the Luke one you linked?

**Comment by linnutee** [comment]
re from matrix:
Title copy would be: SF Decred Devs and Coinbase Custody Happy Hour

**Comment by linnutee** [comment]
Might just go with the cb logo + dcr logo and the title?

**Comment by marcelolustosa** [comment]
![dcr--coinbase](https://user-images.githubusercontent.com/39598223/59805790-9dcbbb80-92c8-11e9-84f2-81b305e4d05f.png)

**Comment by maxbron08** [comment]
Thanks all! looks great
