### ISSUE TITLE
Politeia Digest new graphics

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdesign#166]
I have worked my way through the last batch of images (#134), more please!

**Comment by linnutee** [comment]
Yep these may drag a bit, if you get in a hurry with the next post do just use one from a previous release and potentially consider rotating to another angle or so.

**Comment by RichardRed0x** [comment]
That's ok I already re-used one and about to re-use another.

**Comment by saender** [comment]
@RichardRed0x https://github.com/decred/dcrdesign/issues/171

**Comment by linnutee** [comment]
@RichardRed0x small hint on better use of the template. When the text (in this case month and dates don't fit into the template) the white container can be increased in width accordingly. This is done either by unlocking the container element (icon on left corner when selected), selecting it and dragging the right side further or by selecting it and increasing the "w" value in the top right XD toolset. W value increases by default from the right side of the container.

All the copy should be always left aligned and have symmetrical spacing/padding on the left and right side. Right now the second row copy (date) is misaligned with the first row as well has less padding, thus won't look as clean.

Feel free to try to get it sorted to better practice the use of the template or use / compare against the updated one in attachment. 

<img width="1909" alt="Screenshot 2019-09-13 at 18 58 47" src="https://user-images.githubusercontent.com/17774057/64877114-636c8300-d659-11e9-807a-78cf8acbe930.png">

<img width="1670" alt="Screenshot 2019-09-13 at 18 52 25" src="https://user-images.githubusercontent.com/17774057/64876641-3ff50880-d658-11e9-965a-3e9543d4cbb7.png">

[decred  - pi digest - templates - 0919.xd.zip](https://github.com/decred/dcrdesign/files/3610775/decred.-.pi.digest.-.templates.-.0919.xd.zip)

**Comment by RichardRed0x** [comment]
Thanks, I was wondering about this. Will put this into practice next time.
