### ISSUE TITLE
"Decred Journal" august issue images

### ISSUE THREAD

**Issue by saender** [decred/dcrdesign#169]
Images for GH, Twitter, Medium and Facebook release.

Preview:
<img width="529" src="https://user-images.githubusercontent.com/29069168/64364471-97252880-d01b-11e9-829c-5f114059ab45.png">

Package:
["Decred Journal" august image package.zip](https://github.com/decred/dcrdesign/files/3580506/Decred.Journal.august.image.package.zip)

Title:
Key Symmetry

**Comment by xaur** [comment]
@saender that's beautiful! Is there any background text in addition to the title?

Is the big cube the privacy release?
