### ISSUE TITLE
Twitter images cheatsheet

### ISSUE THREAD

**Issue by saender** [decred/dcrdesign#17]
A Base formula to standardize and streamline Twitter images which include main post categories with logic, composition, prototype and examples.

[decred - twitter images - cheatsheet.pdf](https://github.com/decred/dcrdesign/files/2042457/decred.-.twitter.images.-.cheatsheet.pdf)

![decred_-_twitter_images_cheatsheet](https://user-images.githubusercontent.com/29069168/40584728-952bba3a-61ae-11e8-9e45-2c1f9e6a31cb.jpg)

**Comment by linnutee** [comment]
The latest .ai templates can be found here: https://www.notion.so/eeter/Decred-Twitter-Images-Cheatsheet-fe910bf56be34a72b9d11d8e8e034670

**Comment by denyszayets** [comment]
this is great. Finally we don't have to spend 2 hours debating on what icon to use :D
