### ISSUE TITLE
Title image request for book type resource

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdesign#174]
I have written a book type resource titled "Peer Production on the Crypto Commons" and would like to request a title image to use on its website and title page. The idea is to view blockchains as common pool resources that are actively constructed by different constituencies (miners, developers, stakers, merchants, users, exchanges). The strongest and most interesting blockchains do more of their production (especially the governance) "on the commons". In some of the writing the idea of the commons as a physical space with different entities is used (like a big opaque monolithic corporate or foundation appearing as a black box which dominates the commons of some ICO projects). The idea of a "commons" has historically been associated with physical spaces like grazing land, irrigation systems or forests, but it is often used now in relation to the "digital commons". The book is about different constituencies working together (and sometimes being in conflict) to make things (blockchains) on the commons.

**Comment by saender** [comment]
https://github.com/decred/dcrdesign/issues/176
