### ISSUE TITLE
Dcrpool UI redesign and UX improvements.

### ISSUE THREAD

**Issue by dnldd** [decred/dcrdesign#178]
### Current Feature Set

- **Automatic UI Updates** : The user interface automatically updates block heights, mined blocks, pool hash and other pool related data when updated values are received. I think the `pool information` section could use more emphasis (bold font, highlight colors) making the data displayed more glanceable. 

- **Pseudonymous account management**: The pool uses only mining addresses to identify users, there are no traditional user accounts as a result. Account management is done via the mining address of the user. Currently when a user searches for their mining address they are presented with:
     - the number of miners using the mining address searched for.
     - the hashrates of the miners using the mining address searched for.
     - the payments made to the mining address.
     - the blocks mined by a miners using the mining address searched for.

I think the current ui/ux of account management can be improved and made more presentable.

- **Admin Dashboard**: The pool allows an administrator using a admin password to access the admin panel of the pool. The admin panel lists all connected miners to the pool and their associated hashrates. It also provides database backup functionality using a backup password. The current ui/ux admin section isn't great, needs simplification and improvement.

- **Miner Connection Details**: The pool has a section which shows connection details needed to connect a supported miner to the pool. This section is the `miner configuration` section in the current ui. It's a simple text section, I think it needs more emphasizes since it's the first thing that a new miner should notice when looking at the pool. An illustration coupled with the connection details here might better communicate its purpose.

- **Navigation**: The pool currently has most of the features provided on a single  page with the admin page link tucked at the bottom. It'd be nice to properly separate functionality into different pages and provide easily noticeable navigation for it, like what [dcrdata](https://explorer.dcrdata.org/) has.

### Upcoming features

- **Payment Requests**: A planned feature of the pool will allow miners to request for payments owed them via the pool ui. This feature will be limited to a set number of requests every month for a user.

- **Pending payments**: Currently the detailed account breakdown does not show pending payments to the user's mining address. This is a prerequisite for implementing user payment requests and a missing piece for payment analysis.

### Usecases

1. Miner A feels he/she has missed a couple of payments from the pool and would like 
some clarity on the matter.

    **Action**: Miner A, with his/her mining address should be able to search for payment
 details related to the mining address he/she is interested in.

   **Result**: Miner A should receive a detailed summary of payments made and pending 
payments to the mining address provided as well as the blocks those mining 
payments originate from for reference.
 
2. Miner A is would like to confirm the hashrates his/her miners are mining at.

    **Action**: Miner with his/her mining address should be able to search for associated 
miners of the address and their statuses.

    **Result**: Miner A should receive a detailed view of miners indicating the miner type 
and current hash rates, associated with the provided mining address.

3. Admin B would like an overview of mining operations.

    **Action**: with the admin password, Admin B should gain access to the admin dashboard 
of the pool.

    **Result**: Admin B should receive a comprehensive summary of pool operations which constitute a list of all connected miners, total revenue made from pool fees, last block mined, outstanding payments to be made and the option to backup the pool database.

One more thing of note is that the current UI does not follow the decred ui and colors spec, this redesign should correct that as well.

**Comment by linnutee** [comment]
I believe these were all done. @MariaPleshkova do drop the assets for archiving. 

https://xd.adobe.com/view/a814493c-193a-4dfc-5735-0e6d459a6924-de25/ ?

**Comment by MariaPleshkova** [comment]
Preview: https://xd.adobe.com/view/a814493c-193a-4dfc-5735-0e6d459a6924-de25/

Spec: https://xd.adobe.com/view/a814493c-193a-4dfc-5735-0e6d459a6924-de25/

XD file: [Dcrpool_27.03.2020.xd.zip](https://github.com/decred/dcrdesign/files/5068173/Dcrpool_27.03.2020.xd.zip)
