### ISSUE TITLE
politeiagui: RFP design

### ISSUE THREAD

**Issue by lukebp** [decred/dcrdesign#183]
The Request For Proposals (RFP) workflow that we've seen used on politeia has been formalized in decred/politeia#1054.  See 1054 for a description of the RFP process. An example of proposals that would use this workflow would be the market maker proposals.

RFP propsoal
https://proposals.decred.org/proposals/30822c16533890abc6e243eb6d12264b207c3923c14af42cd9b883e71c7003cd

RFP submissions
https://proposals.decred.org/proposals/2eb7ddb29f151691ba14ac8c54d53f6692c1f5e8fe06244edf7d3c33fb440bd9
https://proposals.decred.org/proposals/4becbe00bd5ae93312426a8cf5eeef78050f5b8b8430b45f3ea54ca89213f82b
https://proposals.decred.org/proposals/82ce113827140caaaf8b5779ab30402d3ed39f1911fdd2e8fa64cf0dc9e09ecb

1054 hasn't been merged into master yet, but the overall RFP process and the politeia API have been finalized so the design work for it can begin at any point.  Here's a rough overview of the changes that will need to be made to the gui.

Proposal submission page:
- The ability to specify that a proposal is an RFP and the ability to set the RFP deadline.
- The ability to specify a proposal link.  RFP submissions link to the RFP proposal, this is how we know that they are RFP submissions.

Proposal details page:
- There should be a list of all the proposals that have linked to the proposal being displayed.  RFPs are the only types of proposals that can be linked to at the moment, but this will also be used to display proposal updates in the future.
- If the proposal being viewed has linked to another proposal, this should be displayed somewhere on the proposal details page.

Proposal list views:
- Its now possible for a proposal to meet the quorum and pass requirements during a vote, but to still be considered rejected.  There will need to be some sort of indicator on the proposal list card to indicate that this proposal was an RFP submission and was part of a runoff vote.

**Comment by MariaPleshkova** [comment]
Specs: https://xd.adobe.com/view/44a3298e-a814-42b2-643e-3aa39c8dec34-3292/

**Comment by MariaPleshkova** [comment]
XD file: [RFP_17.02.2020.zip](https://github.com/decred/dcrdesign/files/4236065/RFP_17.02.2020.zip)

**Comment by amassarwi** [comment]
Hey @MariaPleshkova 
Specs looking good! 
One small observation, we will need the `rfp` icon/logo as .svg file, would be great if you attach to this issue as well.

**Comment by MariaPleshkova** [comment]
@amassarwi do you mean this blue tag?
![image](https://user-images.githubusercontent.com/8841018/75332404-6076ef00-5895-11ea-8100-707a3812f7cc.png)

**Comment by amassarwi** [comment]
@MariaPleshkova yep

**Comment by MariaPleshkova** [comment]
@amassarwi added to my comment with xd file above

**Comment by amassarwi** [comment]
@MariaPleshkova awesome, thanks!
