### ISSUE TITLE
DCR Dex Proposal Images

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#19]
A set of images for the articles and media use.
![dcr dex header - 900px](https://user-images.githubusercontent.com/17774057/41250262-11264daa-6dbf-11e8-8ef5-5de63190eb67.png)
![dcr_-_dex_-_2048px 02](https://user-images.githubusercontent.com/17774057/41250305-2c03d43a-6dbf-11e8-802b-7918e453ce37.png)

[dcr - dex set.zip](https://github.com/decred/dcrdesign/files/2091249/dcr.-.dex.set.zip)

**Comment by denyszayets** [comment]
can you please share editable files? On most of the slides you have an icon + english title. Thanks
