### ISSUE TITLE
dcrweb 01.2020 updates

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#193]
Preview: https://xd.adobe.com/view/b7c058f2-e6e2-486f-65b9-2ca91a14a95a-c1f1/
Specs: https://xd.adobe.com/view/e408f4c8-f66f-4129-7c04-aedfe07adc9d-9239/
XD: [dcrweb - updates - 0120.zip](https://github.com/decred/dcrdesign/files/4134582/dcrweb.-.updates.-.0120.zip)

**Assets**
Graphics (source + optimized): [dcrweb - graphic assets - 0120.zip](https://github.com/decred/dcrdesign/files/4134654/dcrweb.-.graphic.assets.-.0120.zip) 
Subpage headers motion and source - https://github.com/decred/dcrdesign/issues/144
Explainer and subpage shorts: https://www.notion.so/eeter/Decred-Explainer-12-2019-2233a78c498c4224a5be29443856a435

The key visuals (landing page + subpage headers) as well motion bits should be all gathered up there. The content visuals in the newsubpages are done for the most part, besides History subpage, which will be followed up on shortly.

Two first images on sustainability may be re-addressed as a render for more consistency, though these are also ok as placeholders. The third image should be replaced down the line with ideally UI example of CMS, when that is present. 

The short versions of the explainer are meant for each subpage and long version (whether with or without longer ending, @dustorf call on landing page).

**Comment by linnutee** [comment]
Posting a list of needed tweaks, this are for the most part rather minor but add up in the bigger picture: https://xd.adobe.com/view/d393abeb-3c02-432c-766c-2fd3dc7cdb10-a5a2/

1. On landing page, the Download button's center spacing between type and icon is slightly off, too large. 

2. Landing page, spacing of the first card should slightly overlap into the header area in order to visually bridge the page. Right now aligned with sections. 

3. Landing page, big cards: The active areas of the cards are not fully working. Idea was to allow for the title and copy to also work as a active area which upon clicking takes the user to the subpage. The css hover for this display a `→` behind the title and reduce the opacity of the dark-blue gradient layer ontop of the image. 

4. Landing page, posts: bottom edge has noticeably large spacing. 

5. Landing page: language picker seems to trigger the main nav, these should not affect one another. 

6. History page: small one but the circles being 1px misaligned against the vertical line really stand out. 

------- 

Follow-up after initial release: 
Motion assets: 
The idea with the landing page's cards was to use motion graphics as part of the hover effects. I did some quick renders, sizes seem still a bit larger to include 3 or 5 of those there, so would not pursue them right off. I think we can get to a reasonable size, but will address after initial release. So these can just be still images and perhaps with subtle scaling css transition (on hover, ie. ease-in-out 210ms + scale to 120%)

History page symbols actually have animated versions of them existing. @kyleFirethought can look into exporting the json (lottie) versions w/ the given color scheme, would also need some dev to see how to get those implemented. 

There's a number of further visual design tweaks + css finessing, but i'll address those after the initial release in order not to block the workflow.

**Comment by linnutee** [comment]
Landing page cards (still) (tinfied): [dcr - landing page  cards - 939x450@2x .zip](https://github.com/decred/dcrdesign/files/4149734/dcr.-.landing.page.cards.-.939x450%402x.zip)

**Comment by linnutee** [comment]
Community icons (nav + footer): [dcrweb - nav and footer icons - 0220.zip](https://github.com/decred/dcrdesign/files/4152925/dcrweb.-.nav.and.footer.icons.-.0220.zip)
Default state: #E9F8FE
Hover: #FFFFFF

**Comment by linnutee** [comment]
Added the last missing content visual for History / Decred Project Origin paragraph. 
[decred-project-origin@2x.zip](https://github.com/decred/dcrdesign/files/4165567/decred-project-origin%402x.zip)

**Comment by linnutee** [comment]
Added all the symbols used on the history page / principles section. Update all the previous ones to these latest svg's for consistency. 

fixedFiniteSupply.svg
freeAndOpenSourceSoftware.svg
freeSpeechAndConsideration.svg
incrementalPrivacyAndSecurity.svg
multiStakeholderInclusivity.svg
universalFungibility.svg

[dcrweb - history subpage - principle symbols.zip](https://github.com/decred/dcrdesign/files/4233213/dcrweb.-.history.subpage.-.principle.symbols.zip)

**Comment by kyleFirethought** [comment]
All the elements should have JSON exports, I'm pretty sure that export in a given colour scheme wouldn't be required given these are all vector elements. Happy to work with someone to test out implementation.

**Comment by kyleFirethought** [comment]
Batch 1 for review.  Others should be complete by EOD today. @linnutee.

![free_speach_consideration_2](https://user-images.githubusercontent.com/7825971/78891425-731d4000-7a5f-11ea-9ece-bd750b191d69.gif)
![stakeholder_inclusivity](https://user-images.githubusercontent.com/7825971/78891427-731d4000-7a5f-11ea-9296-9f61e349ed12.gif)Bat
![universal_fungibility](https://user-images.githubusercontent.com/7825971/78891422-71537c80-7a5f-11ea-852c-7ae418cf156d.gif)

**Comment by kyleFirethought** [comment]
Batch 2:
![fixed_finite_supply](https://user-images.githubusercontent.com/7825971/78911308-0d8c7c00-7a7e-11ea-963e-153329bb83d9.gif)
![free_open_source_software](https://user-images.githubusercontent.com/7825971/78911325-13825d00-7a7e-11ea-9c67-4e765fcfa3b9.gif)
![privacy_security](https://user-images.githubusercontent.com/7825971/78915437-d620ce00-7a83-11ea-9e57-568afcddf6c4.gif)

Let me know you thoughts @karamble @linnutee and once I get your feedback I'll get the animations prepared for a .json export.

**Comment by linnutee** [comment]
Hey, sry took a tad bit longer to get back on these. I think all look good animation-wise. The only item i'd consider re-iterating slightly is the open source code. Meaning the outer "<" ">" could pop out once the code is finished as symbol-wise it's perhaps not the clearest notion on being open source. But if that looks off, can go with it. 

Only concern is do all also start from a complete state (same as on still). Asking this as if this plays back on a hover state, that there wouldn't be any jumpiness (going from the default static icon to the 1st frame state)?

**Comment by kyleFirethought** [comment]
@linnutee 

Re: time remapping - no worries whatsoever
Re: open source - no worries - I'll make those changes and get over updated .gifs and some .json files.

**Comment by kyleFirethought** [comment]
@linnutee @karamble 
Please see this issue: https://github.com/decred/dcrdesign/issues/206
.json files have been uploaded for your review.
