### ISSUE TITLE
blog.decred.org image needed

### ISSUE THREAD

**Issue by Dustorf** [decred/dcrdesign#196]
I have an extended blog that will go up on decred.org blog, and I'm in need of an image for web and twitter. 
The blog covers:
-a synopsis of budgetary expenditures in 2019
-an evaluation of what worked and what didn't
-prescriptions for community marketing in 2020

It's 4-5k words, so fairly lengthy. LMK if you need any direction, but you guys generally do a great job. The main themes going forward are:
-decentralize
-break the bubble
-the power of each individual community member

**Comment by linnutee** [comment]
Attachment below + notes:

**dcr - marketing report 19 - 900x600@2x (for blog).png** is intended for blog.decred.org only as it's without title and compressed through tinypng. 

**dcr - marketing report 19 - 1024x512 (for twitter).gif** motion bit is with title is for the accompaning twitter post or any other social media publishing. 

[dcr - marketing report 2019 - graphics.zip](https://github.com/decred/dcrdesign/files/4230902/dcr.-.marketing.report.2019.-.graphics.zip)
