### ISSUE TITLE
Thumbnail Request: "Can You Trust Your Bank"? Panel Feat. Marco Peereboom - Web Summit 2019 Highlights

### ISSUE THREAD

**Issue by exitus1** [decred/dcrdesign#198]
I put together a highlights video for the panel that Marco was on at Web Summit 2019 "Can You Really Trust Your Bank"?

Requesting a Thumbnail that is artistically similar to the ones currently on DCR's YT channel in order to maintain conformity.

**Comment by linnutee** [comment]
![dcr - yt thumb - websummit19 marco](https://user-images.githubusercontent.com/17774057/76764763-11d6b980-679e-11ea-85bc-aff16a7f8b47.png)
