### ISSUE TITLE
Facebook Cover Video

### ISSUE THREAD

**Issue by dezryth** [decred/dcrdesign#199]
Design Team,

Can you please provide an updated video that can be used for the cover video on Decred's facebook page? We are in the process of updating messaging to match the new website design. Similar format to last one is okay; perhaps "Decred is a Community-Directed, Superior Store of Value" instead of current verbiage in lower left corner. The moving image on the /security/ or /sustainability/ page would look great, but I will leave this to your discretion :)  

Requirements (https://www.facebook.com/help/132465104004008)
Must be between 20-90 seconds long.
720p resolution minimum
.MP4 format

I read that the resolution requirement Facebook provides isn't strictly necessary and in some cases doesn't look as great. I may need to try more than one resolution to find the right fit. Thanks for your help! Please reference previous issue if necessary: https://github.com/decred/dcrdesign/issues/44

**Comment by kyleFirethought** [comment]
Happy to work on this, the only requirement is the latest version of the explainer.  @linnutee can you please point me in the right direction here?

**Comment by linnutee** [comment]
Right, gave this bit of a thought - should actually update all of the social media headers in order not to break consistency. Iirc facebook is the only one what allows for some motion piece, so when you got something in mind do share in riot for reviewing as that way we can align any updates to twitter and such as well. 

The high res mp4's are here: https://www.notion.so/eeter/Decred-Explainer-12-2019-2233a78c498c4224a5be29443856a435 considering the fb res, these should likely provide enough resolution to work with.

If you need the prores, i'll wetransfer those. Also if needed we can include Tuomas for any modifications beyond the renders.

**Comment by kyleFirethought** [comment]
@linnutee Perfect, I'll have a look through all these and drop you a message if any further documents are needed.

**Comment by kyleFirethought** [comment]
@dezryth @linnutee,

I've exported a short loop for social to FB's given spec.  Let me know if there are any issues with this and I'll provide a slightly higher resolution piece.

Attached are previews of said video as an image thumb as well as the loop itself.

[DCRFacebookCover_05_2020.zip](https://github.com/decred/dcrdesign/files/4576878/DCRFacebookCover_05_2020.zip)
![Loop Preview](https://i.gyazo.com/f20d10fff181b67edc09fffd70902e02.gif)
![Thumb Preview](https://i.gyazo.com/e789403d6e2b9421383759ca4bf50caf.png)

**Comment by kyleFirethought** [comment]
@dezryth @linnutee 

I've uploaded this is a range of different resolutions which should cover every edgecase.

https://drive.google.com/file/d/111zSr4C4GvGOeZi56dhqyQjdT6AdpK_S/view?usp=sharing - _Recommended_
https://drive.google.com/file/d/1hxyKmvOQKvhUFh0YST45ZPTGX1HaIWtM/view?usp=sharing - HD
https://drive.google.com/file/d/1OqOgEbX9jteXcg_AgXxWIMCDezUN6vcR/view?usp=sharing - Supersized

Reopen if there are any issues.
