### ISSUE TITLE
Contributor portrait for guisso

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdesign#201]
Please can we get a contributor portrait for guisso?

@guisso:decred.org on Matrix
github.com/fguisso

**Comment by marcelolustosa** [comment]
@guisso @jholdstock I need his photo!

Please check this for photo guidelines: 
https://github.com/decred/dcrdesign/issues/47

**Comment by marcelolustosa** [comment]
[Guisso.zip](https://github.com/decred/dcrdesign/files/4439910/Guisso.zip)

There's it

**Comment by jholdstock** [comment]
Thanks a lot!
