### ISSUE TITLE
Visual Guidelines: create a criteria for platform logos

### ISSUE THREAD

**Issue by oiezz** [decred/dcrdesign#202]
Currently, there are no distinct visual guidelines that separate marketing symbols (privacy, free speech, etc) vs. platform symbols (Pi, LN, etc). The colors and motif are similar. 

As more decred assets are built, platform guidelines could visually communicate groups more distinctly.

**Comment by linnutee** [comment]
Well it does makes sense to update the visual guidelines in the near future, as quite a bit of new assets has been created. I'll list this issue down when doing so. What you've pointed out is actually covered to quite some degree, so i'll elaborate a bit: 

- Decred logo and (and its variants) is a top of the hierarchy asset. This has quite defined use rules as well various suggestions what's more appropriate and where. 

- Politeia has a standalone logo, as Pi is a higher level and also sort of stand-alone platform in the dcr ecosystem. Ie. there's been comms. efforts made on how Pi could be used in various other contexts besides being DCR's proposal system. Therfore it has a unique symbol, and the symbol also refers back to DCR by following similar means of construction and styling. 

- The various platforms and projects such as dcrdata, dcrtime, dcrdocs, vsp's etc often use what's called a "derivative logo". These logos are made up from a lockup using the DCR symbol and the platforms or projects name. Ie. https://user-images.githubusercontent.com/17774057/55497540-3fd4f380-564a-11e9-97f3-eeb60c51fd90.png. This is actually something not yet present in the guidelines as well has somewhat hectic use that's not really been properly aligned yet. So most relevant point here.

The rest of the items mentioned are graphic assets groups. So for example, 1. icons are typically meant for more functional use which has set a basis for their design and can be used in a number of contrast and color variants depending on the context (ie. UI, keynotes, web). 

Where-as the 2. symbols are more specific to marketing and visual comms use,  being twice as complex as the icons, so covering bit larger topics. These were originally created for an early version of DCR roadmap + the community principles, and found gradual use in other various visual comms. 

In rare cases like LN, there is for example both a derivative logo for LN, which is suited for specific marketing/comms context and an icon (practical UI) and a symbol for others (roadmap).

**Comment by oiezz** [comment]
Thank you for offering to list this issue down when you update the visual guidelines. I agree that most of your guidance is sufficient except for the derivative logos. In time, I imagine several will take on greater significance and may merit a standalone symbol. To that point, it remains unclear to me when a unique symbol should be applied as many of them can be used for other contexts. 

Alternatively, if we create symbols for all derivative logos then we can focus on defining the properties/purpose each platform has and the interconnections they have between each other.

**Comment by linnutee** [comment]
https://github.com/decred/dcrdesign/issues/266
