### ISSUE TITLE
Lottie updates

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#206]
General Issue for the update of Symbols and Identity Icons with .json pieces.

Icons that have been meticulously animated over the years have been left to the side despite many appropriate applications being actively worked on.  

For this reason, this library has been uploaded to an online repository with the relevant tools to support Developers and Front End Designers leverage the work that was undertaken to improve the UX of Decred's products.

Lottie Files has a File Editor that allows Artists and Developers to amend and change the .json without needing Adobe After Effects or needing to get stuck into the code.  This should sufficiently lower the barrier of entry for those working on Decred applications for both Desktop and Mobile platforms. 

**Editor:**
![Image of Lottie Editor](https://i.gyazo.com/d5c03e1a4ae4b136a4be24ac5efc82c2.png)
Lottie Editor: https://www.youtube.com/watch?v=6KNUp6HTAhs
Equally, these are all hosted on Lottie Files meaning that you now don't have to download all the .gifs in order to access the .json files in the original icon-set substantially lowering the barrier of entry.
![Image of Decred Account](https://i.gyazo.com/47c57299f6d50145292a5545a149debb.png)
You can find all animations on the Decred Project account: https://lottiefiles.com/decred

**After Effects Import:**
These animations can now be re-imported back into AE allowing for future contributors to tweak and build upon designs. when required.
For this the Bodymovin.js Plug-In is required: https://aescripts.com/bodymovin/

**Telegram Stickers:**
![Image of Decred Account](https://i.gyazo.com/6b247b45bdf8291759188ab17308088b.png)
.TGS Telegram sticker files can easily be created in the Lottie Editor.  Resize and re-time the animation to 512x512 and make sure that the animation is no longer than 3 seconds.  Then all you need to do is press download .TGS located in next to download JSON for Lottie.  You can create animated sticker packs through the Telegram Sticker Bot.
![Image of Telegram Sticker Bot](https://i.gyazo.com/923193c6cbcfec396a52bd357f1fd4af.gif)
**GIF:**
![Image of GIF Download](https://i.gyazo.com/1667252b7f75d3d540c3914a69c53fa7.png)
GIFs of the animations can be downloaded from Lottie Files.  Simply click on the file of interested and click on the three dots next to "JSON" where you should be given the option to download a GIF and resize to a suitable size.

**Lottie files:**

DCRDEX:

 - primary

 - open
 - loop

Decred Logo:

https://lottiefiles.com/share/3soUmG - primary
https://lottiefiles.com/share/8RXaT5 - vertical
https://lottiefiles.com/share/nH0xu4 - vertical alt

https://lottiefiles.com/share/pTCQ7s - open
https://lottiefiles.com/share/xSNuPc - loop

https://lottiefiles.com/share/FkfFw9 - spinner loop

Politeia Logo:

https://lottiefiles.com/share/UhX8Ml - vertical
https://lottiefiles.com/share/MybLtP - horizontal

https://lottiefiles.com/share/YqVO3Z - open
https://lottiefiles.com/share/OC2Iz6 - loop

https://lottiefiles.com/share/9tHHo4 - spinner loop

Symbols:

_Website20_

https://lottiefiles.com/share/rIBrHW - privacy
https://lottiefiles.com/share/X1a13x - free speech consideration
https://lottiefiles.com/share/r81jI1 - open source software
https://lottiefiles.com/share/agg1dU - stakeholder inclusivity
https://lottiefiles.com/share/hs099H - universal fungibility
https://lottiefiles.com/share/0iuVGr - fixed finite supply

_Roadmap18_

https://lottiefiles.com/share/giIC5W - spv
https://lottiefiles.com/share/JbiDg7 -security
https://lottiefiles.com/share/uolwUM - scalability
https://lottiefiles.com/share/CZ1Za7 - marketing growth
https://lottiefiles.com/share/7fe5oU - dae
https://lottiefiles.com/share/94KptK - decfunds
https://lottiefiles.com/share/ZIP12e - airdrop
https://lottiefiles.com/share/YcYQ1T - intergrations

_Symbols18_

https://lottiefiles.com/share/ptN80u - atomic swap
https://lottiefiles.com/share/b47BNz - lightning

_Iconset18_
All current icons that support Lottie are available on the DCR Project profile:

_Telegram_
https://t.me/addstickers/DCRDesign - Sticker Pack 

If a requirement for further animations is needed - _Hollar in the comment section below._

**Comment by linnutee** [comment]
Solid stuff!

**Comment by kyleFirethought** [comment]
![animation_300_kaehuan5](https://user-images.githubusercontent.com/7825971/82385193-6c53f680-9a29-11ea-8e39-6e6475e983d8.gif)
![animation_300_kaehufv1](https://user-images.githubusercontent.com/7825971/82385195-6d852380-9a29-11ea-98a8-e6b1b9366a1f.gif)
![animation_300_kaehwzek](https://user-images.githubusercontent.com/7825971/82385198-6e1dba00-9a29-11ea-98ba-ce1c0b4564b4.gif)

@linnutee DCRDEX 1st Draft.

**Comment by linnutee** [comment]
Looks great! These illustrate the metaphors quite well. Did you try without the semi-transparent bg layer also for the complete logo? I see it making sense in instances where it's looping, but wonder if its simpler & cleaner w/o when purely transitioning in.

**Comment by kyleFirethought** [comment]
_Changes:_
Better matte for the strokes should provide seamless masking of the element in Lottie version for use in pattern form.  This also benefits the GIF at higher resolutions. 
-
Other versions showing the animation of "successful, unsuccessful and cancelled" variations. 
-
Removal of the bg (this is preferred generally because it means GIFs with Alpha can be exported without issues). 
-
_Open_
![dcrdex_open](https://user-images.githubusercontent.com/7825971/82498090-4d1b9e80-9ae7-11ea-9767-31b138545810.gif)
_Loop_
![dcrdex_loop](https://user-images.githubusercontent.com/7825971/82498100-50af2580-9ae7-11ea-9783-2cd3ee78bba6.gif)
_Successful_
![dcrdex_open_successful](https://user-images.githubusercontent.com/7825971/82498158-66244f80-9ae7-11ea-96ca-1fba72590717.gif)
_Unsuccessful_
![dcrdex_open_unsuccessful](https://user-images.githubusercontent.com/7825971/82498080-4856ea80-9ae7-11ea-9916-866a247f25bc.gif)
_Cancelled_
![dcrdex_open_cancelled](https://user-images.githubusercontent.com/7825971/82498064-3ffeaf80-9ae7-11ea-934d-df213ec300f4.gif)
_Primary_
![dcrdex_primary](https://user-images.githubusercontent.com/7825971/82498047-37a67480-9ae7-11ea-9d6e-3cfb3dce79f7.gif)

@linnutee Either works well, just depends on the context I guess, in line with the notes above it would help to have this without.  This does help for the tx status variations and could help to export both as (from the offset) users may not immediately make the connection with the pattern, especially if it is used in the absence of the patten.

**Comment by kyleFirethought** [comment]
Will close this issue for the time being, no updates.
