### ISSUE TITLE
piui <> decrediton – Map out components

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#213]
Hey @amassarwi, I've recently synced up with @harlovski and @MariaPleshkova regarding the piui developments. Making this issue to start the design support for doing the implementation to Decrediton.

As the development side is a fair bit ahead, and we don't have a synced up design component library its a good time to get this side sorted. Expanding piui's use to Decrediton will likely require some new components to be created, as well its a good time to re-evalute the items that are already in use, ie. how well they are performing and whether something could be updated.

For the outcome of this issue, we should get better awareness on all of the components, by creating a list of them and their status by each product (each product using – piui, this can be grown down the line). Recommend this to be done in notion or somewhere similar with good accessibility. The starting column could be about the component names, organized in the same way as in https://decred.github.io/pi-ui/ and follow-up columns reflect the status in Politeia, Decrediton. Component statuses can be as following: `in use` `ready for use` `no design` `needs refinement` `n/a`

Also @harlovski – useful to keep an eye out on /decrediton for issues tagged with [pi-ui] https://github.com/decred/decrediton/issues/2505

Once this is completed, will follow up with starting off the component library as well getting a couple key examples in order. The idea is to also transition the design process over to Figma, and if everyone is onboard then that can be the pilot project.

**Comment by amassarwi** [comment]
Thanks for this issue @linnutee!

We discussed it in details on matrix's `Decrediton Dev` channel, here are some thoughts:
 - We could track the statuses/usage of the components in pi-ui's docs:
   - Add a status tag to each component's doc page using the `StatusTag` component we already have in pi-ui to display the component status & add small usage table with one column for each product: `politeia`, `decrediton` - can be extended to add more of decred's products (e.g `dcrtime`).
   - Add new menu item to docs something like `Components Usage` to display in one list all components statuses & usage, link to the components pages would be also nice.
-  We should rename the repo name at some point to something more generic to something like `dcr-ui` as we are planning to use it in as much as possible of decred's GUIs.

I would love to get @tiagoalvesdulce's thoughts regarding this issue as well.

**Comment by tiagoalvesdulce** [comment]
It's nice to see that the repo is being useful for projects outside of politeia and I hope we can improve it together. :) I agree with everything you said, @amassarwi. I will be glad to help adapting the repo for all those changes.
