### ISSUE TITLE
"Decred Journal" may issue images

### ISSUE THREAD

**Issue by saender** [decred/dcrdesign#214]
Images for GH, Twitter, Medium and Facebook release.

Preview:
<img width="656" src="https://user-images.githubusercontent.com/29069168/83919502-5fead000-a783-11ea-9878-cd280e7807b9.png">

Package:
["Decred Journal" may image package.zip](https://github.com/decred/dcrdesign/files/4738319/Decred.Journal.may.image.package.zip)

Title:
Ascending Bits

**Comment by xaur** [comment]
I get so excited every time. Thank you!
