### ISSUE TITLE
Thumbnail - Politeia live for Decred BR

### ISSUE THREAD

**Issue by Michae2xl** [decred/dcrdesign#215]
Content: Politeia

Participants: Tiago Alves & Victor Guedes

Link: https://youtu.be/p59iF8hl7lI

**Comment by Michae2xl** [comment]
?

**Comment by linnutee** [comment]
Sry never got to this. Will address over the week.

**Comment by linnutee** [comment]
Hey, added in attachment @Michae2xl 

![decred - pi live br- yt1920px](https://user-images.githubusercontent.com/17774057/91094345-588ce180-e663-11ea-8691-28e7b92d290b.png)

**Comment by Michae2xl** [comment]
Thank you

**Comment by Michae2xl** [comment]
https://youtu.be/p59iF8hl7lI
