### ISSUE TITLE
Decrediton: Improved Staking Onboarding Experience

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#217]
### Introduction:
This will consist of a number of animated assets covering How Does Voting Work? as well as Ticket Lifecycle that will form the basis for a new onboarding experience that guides first-time users through the fundamentals of how PoS functions on Decred's Blockchain as well as what to expect when participating in PoS reiterating it's importance to the network. 

This proposal is a supplementary enhancement on initially proposed tasks outlined in dcrdesign Github issue #104.

**Additional Documents:** 
Please be sure to review the following attached documentation:

- **Narrative Outline:** https://docs.google.com/document/d/1jlLF5rcw3HJ5-g7Ofhsy2L3NLEs2Ku9MF1dReDprYsw/edit#heading=h.rm1r8ht0ben3
- **Project Approach:** https://docs.google.com/document/d/1BsdRZd0m93RwyXlpZ-qKhUqBGGNV-DSV2-AtxSJSti4/edit?usp=sharing
- **Task Breakdown and Estimates:**
- **Figma Project:** https://www.figma.com/file/Brol2kMY2gifB9ffGCAbWi/%CE%A01?node-id=0%3A1

### Production Outline:

**Preproduction:** At this point work on some Storyboard Illustrations translating the idea specified in the Narrative Outline will begin.
Following completion, these concepts will be presented to the community with an animated Animatic (where possible) to contextualise timings. 
**Production:** This is the period where visuals are created, assembled and animated according to the agreed Narrative Outline.
Unless otherwise specified updates would be provided on a scene by scene basis worked upon in a linear fashion until completion.
**Implementation:** At this point, a number of actions will be enacted in the stated order:
Deliverables will be peer-reviewed by fellow Decred design contractors and a Release Candidate presented to the community. 
Project outputs will be uploaded to the relevant Github issue as well as Lottie Files.
Issues will be raised on the Dcrweb and Decrediton repositories for implementation in the next UI/UX Design Master Issue.

_This project is focused on creating a solution for Decrediton and Dcrweb with assets suitable for other applications. The implementation of these assets will be the sole responsibility of those contractors who maintain said applications._

### Project Objectives:
Below are the core objectives that this proposal sets out to accomplish:

**Art:**

- Develop [number of pieces] short animated scenes that effectively communicate key statements outlining the ticket lifecycle. 
- Bring PoS Onboarding materials to the same standard as previously set in the Initial Onboarding materials.
- Removal of textual elements that clash with Decrediton's localization support.
- Further Decred's Stakey character development through motion design.

**Technical:**

- Deliverables that allow for clean implementation across desktop and mobile devices.
- Seamlessly looped animations with a duration of no longer than 12 seconds exported as JSON, GIF and MP4.

**Misc:**

- Updated Onboarding copy.
- Community Outreach facilitated through Livestream Q&A to be reposted across various DCR channels. 

Task Breakdown & Estimates:

The following outputs have been planned:

- How does voting work:
- Ticket Lifecycle:

_All created to the technical specification stated._

### Appendix:

- What is User Onboarding? https://www.trychameleon.com/blog/what-is-user-onboarding
- Dcrdesign: https://github.com/decred/dcrdesign
- Onboarding Slides: https://github.com/decred/dcrdesign/issues/9
- Tutorials layout + Staking tutorials update: https://github.com/decred/dcrdesign/issues/104
- Stakey's Know your ticket - ticket status explained: https://github.com/decred/dcrdesign/issues/51
- Dcrweb: https://github.com/decred/dcrweb
- Decred Constitution: https://docs.decred.org/governance/decred-constitution/
- Dcrweb VSP: https://decred.org/vsp/
- Dcrdocs: Proof-of-Stake (PoS) Voting: https://docs.decred.org/proof-of-stake/overview/
- Safe Area - Wikipedia: https://en.wikipedia.org/wiki/Safe_area_(television)

**Comment by linnutee** [comment]
Continued here https://github.com/decred/dcrdesign/issues/266, closing.
