### ISSUE TITLE
Visual Comms: 1.6 Release Imagery

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#231]
Placeholder issue for required 1.6 Release Imagery.

**Comment by 30000fps** [comment]
![Uploading decred_release_1.6.0.png…]()

**Comment by 30000fps** [comment]
![Uploading decred_release_1.6.0.gif…]()

**Comment by 30000fps** [comment]
![Uploading decred_release_1.6.0.png…]()

**Comment by 30000fps** [comment]
![decred_release_1 6 0](https://user-images.githubusercontent.com/15022929/97036395-12230880-1568-11eb-8577-f1d1d88bda12.png)

**Comment by 30000fps** [comment]
![decred_release_1 6 0](https://user-images.githubusercontent.com/15022929/97036435-1f3ff780-1568-11eb-98c1-86b2632ba67a.gif)

**Comment by 30000fps** [comment]
![decred_release_1 6 0_sm](https://user-images.githubusercontent.com/15022929/97036860-bd33c200-1568-11eb-9732-b637636cefaa.gif)

**Comment by 30000fps** [comment]
[decred_release_1.6.0.mp4.zip](https://github.com/decred/dcrdesign/files/5431018/decred_release_1.6.0.mp4.zip)
+ 12.6 MB MP4

**Comment by linnutee** [comment]
Noice!

**Comment by 30000fps** [comment]
https://user-images.githubusercontent.com/15022929/104227364-8bd0e100-5449-11eb-97e3-f59b15beaf8b.mp4

MP4 / 1920 x 1080 px / 6.6 MB / without type overlay

**Comment by 30000fps** [comment]
![decred_release_1 6 0_0046](https://user-images.githubusercontent.com/15022929/104227722-1fa2ad00-544a-11eb-9562-5a64291307eb.pn
![decred_release_1 6 0_0064](https://user-images.githubusercontent.com/15022929/104227777-32b57d00-544a-11eb-8b52-2c0700b8efa4.png)
![decred_release_1 6 0_0078](https://user-images.githubusercontent.com/15022929/104227788-36e19a80-544a-11eb-90c5-752484121c52.png)
![decred_release_1 6 0_0092](https://user-images.githubusercontent.com/15022929/104227824-452fb680-544a-11eb-87a5-9840218dd944.png)
![decred_release_1 6 0_0095](https://user-images.githubusercontent.com/15022929/104227861-55e02c80-544a-11eb-812c-09d4b6a6d8ed.png)


g)
![decred_release_1 6 0_0051](https://user-images.githubusercontent.com/15022929/104227741-24fff780-544a-11eb-8d45-472c01687510.png)
