### ISSUE TITLE
Illustrations: Know your ticket

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#245]
### Know your Ticket

Given that the Know Your Ticket will go largely unchanged this is the best place to start.

None of the initial pieces were created with animation in mind so it is necessary to go back through these pieces created and do some housekeeping so as not to cause issues further down the road. 

There is also an opportunity here to tweak some of the designs and make improvements where necessary.

**Please sketch any new designs prior to creating production pieces in Illustrator.**

### Checklist:

- [ ] Frame 1
- [ ] Frame 2
- [ ] Frame 3
- [ ] Frame 4
- [ ] Frame 5
- [ ] Frame 6

**Comment by kyleFirethought** [comment]
@marcelolustosa , please reach out for review when this task is complete prior to proceeding to the others,

Thanks,
Kyle.

**Comment by kyleFirethought** [comment]
@marcelolustosa , any update on this front?

**Comment by linnutee** [comment]
Sharing the .ai assets here for archiving. 

Previews/sketches: https://www.figma.com/file/dEqHmYVc2uawBfdOkmKyUi/UX-Onboarding-Storyboards?node-id=53%3A3

Assets: [decred - onboarding assets - know your tickets.ai.zip](https://github.com/decred/dcrdesign/files/7111528/decred.-.onboarding.assets.-.know.your.tickets.ai.zip)
