### ISSUE TITLE
Dcrdex key visual and loop

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#250]
For archiving the files. Variants:
- dex.decred.org landing page, optimization and performance first, up to 1.5 - 2mb, solid color bg, no-bleeding on elements, either same format as decred.org headers or slightly larger.
- HD still 1920x1024 (fine to bleed over edge, can use more colors)
- HD loop 1920x1024 (fine to bleed over edge, can use more colors)

**Comment by 30000fps** [comment]
https://user-images.githubusercontent.com/15022929/109009681-1b0b1e80-76af-11eb-97d2-8f4903756d24.mp4

**Comment by 30000fps** [comment]
https://user-images.githubusercontent.com/15022929/109013967-ff564700-76b3-11eb-9a1c-8fb996f8c944.mp4

**Comment by 30000fps** [comment]
![0087](https://user-images.githubusercontent.com/15022929/109015511-79d39680-76b5-11eb-9bd7-2ffa61866a87.png)

+ PNG / 1600 x 800 px / 0.5 MB / landing page gfx

**Comment by linnutee** [comment]
Tinypng (338kb) and webm (473kb) as well:
[dex - key visuals - tinified.zip](https://github.com/decred/dcrdesign/files/6124816/dex.-.key.visuals.-.tinified.zip)
