### ISSUE TITLE
Request: Bitcoin.com Exchange integration graphic

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdesign#259]
https://exchange.bitcoin.com/

**Comment by linnutee** [comment]
@jzbz 

![dcr - bitcoinexchange com - twitter 1600x900](https://user-images.githubusercontent.com/17774057/128703652-cc627181-ca42-4363-a5b1-c49536d3cd81.png)

Source img: unsplash.com → fakurianarts 👍
