### ISSUE TITLE
Update Politeia challenge YT thumbnails

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#26]
<img width="1349" alt="screen shot 2018-07-17 at 17 04 30" src="https://user-images.githubusercontent.com/17774057/42822393-a05f945a-89e3-11e8-9575-8f882a50803a.png">

The logo on these is broken, so all 9 episode thumbnails should be replaced. Iterate a series visual reference from the Pi challenge hero image

Size: 1920x1080px

Elements to include: 
- latest Pi logo
- title
- talker name

----------
[politeia - logo.zip](https://github.com/decred/dcrdesign/files/2201977/politeia.-.logo.zip)

![pi-challenge-twitter-1024px-updated](https://user-images.githubusercontent.com/17774057/42822676-525e943a-89e4-11e8-99b1-e2aeebb95909.gif)

![tumblr_m7dj2roylr1qav3uso1_r1_500](https://user-images.githubusercontent.com/17774057/42823951-83e5516c-89e7-11e8-8b63-010047fc0f0b.gif)

![politeia-challenge](https://user-images.githubusercontent.com/17774057/42824766-2e397c32-89e9-11e8-86b4-71f8a85b1b96.jpg)

**Comment by kyleFirethought** [comment]
Fixed thumbs were actually sent over straight after but this was never acted on: https://drive.google.com/drive/folders/1pQ4deO_Kpr0VKwLr1xhjXJrKKiBDOOrz?usp=sharing
