### ISSUE TITLE
Update headers motion design

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#27]
Brief for **@30000kfps** 

Phasing out current js headers and replacing with abstract looping .gif's. 
Use abstract geometry (potential for use or further iterations of architectonics studies) to build relation with the subject matter of each page. 

**The pages and keywords reference for kick-off:**
https://decred.org/exchanges/
sine/square/tri pattern movements, trading charts/candles, measurement, value comparison, noise pattern on a timescale, liquidity growth

https://decred.org/contributors/
growth/expansion, uniqueness, beehive, one goal, engagement, superoganism, global ant-colony, filling up empty space/gaps

https://decred.org/community/
discovery, growth/expansion, different layers of communication, ecosystem, interconnected movements

https://decred.org/stakepools/
transformation (this becomes that), algorithmic cornerstone, time; timelocking, flocks of tickets, option variables, vaults of growth, surplus

https://decred.org/downloads/
importing/receiving, emission, mesh of point a to point b movement, progressive flow, downward movement

https://decred.org/press/ (later on known as news page)
accredit, formal visibility, subjectivity vs objectivity, layers of interpretation, approved hype or
generalization

> Out of all, Press/News needs to be the calmest and most subtle, not to interfere with reading larger textual content. 

-----------

**Details:**
**Background color:** #091440
**Size:** up to 3mb (3.5mb the most if worth it). 
**Dimensions:** 1366 x 345px by default/master.

Discuss further about optimization: 
A) Can be smaller dimensions in case of functional seamless patterns are worked out
B) Can be number of renders with same height and different width (575, 768, 991, 1199px) based on the sites breaking points (this way only loads the relevant size)

One static fallback for each gif.
Semi-transparent overlay with same dark blue not included in gif, will be added in html.

**Primary element colors:** #2970FF ; #2ED8A3
**Secondary colors** can be picked from the color scheme if needed: 
<img width="1139" alt="screen shot 2018-07-17 at 18 27 13" src="https://user-images.githubusercontent.com/17774057/42827466-1ac6e7e2-89ef-11e8-93b7-c61ad0f4558f.png">

**Comment by 30000fps** [comment]
Briefs
![decred briefs](https://user-images.githubusercontent.com/15022929/50971916-8bfa1700-14e5-11e9-8b03-f00c329d35bc.gif)
Community
![decred community](https://user-images.githubusercontent.com/15022929/50971922-90becb00-14e5-11e9-8762-887c5f2f2ab9.gif)
Contributors
![decred contributors](https://user-images.githubusercontent.com/15022929/50971925-93b9bb80-14e5-11e9-8ca5-96282ce65baf.gif)
Design
![decred design](https://user-images.githubusercontent.com/15022929/50971927-94eae880-14e5-11e9-9c51-524fc1b3e090.gif)
Development
![decred development](https://user-images.githubusercontent.com/15022929/50971929-96b4ac00-14e5-11e9-80f1-f1f399ec5f14.gif)
Downloads
![decred downloads](https://user-images.githubusercontent.com/15022929/50971932-987e6f80-14e5-11e9-84fb-e5a12f9e9874.gif)
Exchanges
![decred exchanges](https://user-images.githubusercontent.com/15022929/50971936-99af9c80-14e5-11e9-8773-0e8edf32a3e4.gif)
Governance
![decred governance](https://user-images.githubusercontent.com/15022929/50971937-9b796000-14e5-11e9-891e-b6a9d5a3f2fa.gif)
News
![decred news](https://user-images.githubusercontent.com/15022929/50971938-9caa8d00-14e5-11e9-92c0-7e52ee4a61fd.gif)
Roadmap
![decred roadmap](https://user-images.githubusercontent.com/15022929/50972060-e2675580-14e5-11e9-8187-47d5c34e4b1b.gif)
Stakepools
![decred stakepools](https://user-images.githubusercontent.com/15022929/50972013-c2d02d00-14e5-11e9-85bb-6d6368302396.gif)
Unasigned
![decred alt2](https://user-images.githubusercontent.com/15022929/50972213-49850a00-14e6-11e9-9e64-dd46b45d2f96.gif)

**Comment by 30000fps** [comment]
[DecredHeaders_01.2019_MP4.zip](https://github.com/decred/dcrdesign/files/2745576/DecredHeaders_01.2019_MP4.zip)
