### ISSUE TITLE
Decrediton: microanimations and motion design fixes

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#29]
Microanimations @kyleFirethought:
Preview: https://xd.adobe.com/view/ff2e58a0-530f-4015-6c11-24421ef384e5-891f/
Assets: [decrediton - loader icons.ai.zip](https://github.com/decred/dcrdesign/files/2214263/decrediton.-.loader.icons.ai.zip)

As discussed in the call, different loader messages currently using the generic diamond will be integrated into the loader. Microanimations of should be minimal loops, with optimal duration between 210 - 340 ms. 

Export bodymovin/json and @3x-png sequence as fallback (60x60px).

- [x] Blockchain Loading
- [x] Establishing RPC connection
- [x] Discovering Addresses
- [x] Scanning Blocks for Transactions
- [x] Fetching Block Headers
- [x] Finalizing Setup

------

Fixes and assets @linnutee: 
- [x] Pending tx microanimation re-implementation 
- [ ] Generic loader re-size, color fix, positions fix
- [ ] Stakey re-size

**Comment by kyleFirethought** [comment]
[lottie_loaders.zip](https://github.com/decred/dcrdesign/files/2283851/lottie_loaders.zip)
lottie_loaders including .json + .xml (Android Drawable Vector) + demo preview files for testing in decrediton.

**Comment by kyleFirethought** [comment]
[loaders_fallback.zip](https://github.com/decred/dcrdesign/files/2283906/loaders_fallback.zip)
60x60 png and gif fallback.

**Comment by kyleFirethought** [comment]
![rebroadcasttx_loop](https://user-images.githubusercontent.com/7825971/44046331-0db6f03a-9f23-11e8-8b17-f84da5eec909.gif)
![rebroadcasttx_opener](https://user-images.githubusercontent.com/7825971/44046336-0f07a326-9f23-11e8-9a87-bf10e9c8762d.gif)
Testing opening and loop gifs for rebroadcastTx. micro_lottie and micro_fallback includes all necessary files. 
[micro_pack.zip](https://github.com/decred/dcrdesign/files/2283940/micro_pack.zip)

**Comment by linnutee** [comment]
Coming along well. 

1 Code bit is probably good to go with. 
2 Turning buttons, good to go with or consider fine-tuning speed
3 Block – good to go with (bottom one is better)
4 Establishing RPC: The pumping (scale up/down) makes it way too excessive. Perhaps some non-linear trim-path motion between the strokes, using the middle ones also. 
5 Discovering addresses (wallet): Same case with pumping the circle, can be just a more refined motion (maybe use of the metaballs?) around the "…"
6 Rebroadcast: definitely top one, as that focuses only on the core idea.

**Comment by kyleFirethought** [comment]
![finalizing_setup_loader](https://user-images.githubusercontent.com/7825971/44167533-53851700-a0c6-11e8-975e-0d113bf96f76.gif)
![scanning_blocks_loader](https://user-images.githubusercontent.com/7825971/44167536-5849cb00-a0c6-11e8-81cf-0b40d4e1fdf2.gif)

The searching animation seems to have slipped through the net. I've now lengthened the comps to a maximum of 00:01 @30fps, which is slightly more than initially stated but it's needed in some cases here, optimisations can be made where necessary later.

**Comment by kyleFirethought** [comment]
Agreed, Any chance you can fire over a blank template for me to test them out with? - Cheers.

**Comment by kyleFirethought** [comment]
[animated_loaders_16_08_2018.zip](https://github.com/decred/dcrdesign/files/2292014/animated_loaders_16_08_2018.zip)

**Comment by linnutee** [comment]
Yah alright. I'd say the rest are good to go with, only  "Blockchain Loading" should be tad bit smoother and slowed down. Perhaps also flip it, so the block would grow from left bottom corner to top right (positive growth direction).

**Comment by kyleFirethought** [comment]
Microanimations deliverable: Block Sync slowed from 01:00 to 02:00. 
[loading_microanimations_17_08_2018.zip](https://github.com/decred/dcrdesign/files/2295037/loading_microanimations_17_08_2018.zip)

**Comment by kyleFirethought** [comment]
![pendingdots](https://user-images.githubusercontent.com/7825971/44340344-745dbb80-a47c-11e8-8299-e9c31ca5be73.gif)

Just looking at the list, I remember the original spec for the pending dots which was so low that antialiasing made any GIF just fall apart. could be a viable use for Lottie. I had time over the weekend to put this little zip together to the spec of the previous icons, pendingDots solo'ed. 

Let me know how you'd like to proceed as I'm quite keen to tick off this list before I head off. 👍 

[pendingTx_microanimations_19_08_2018.zip](https://github.com/decred/dcrdesign/files/2302327/pendingTx_microanimations_19_08_2018.zip)

**Comment by kyleFirethought** [comment]
![pendingdots](https://user-images.githubusercontent.com/7825971/44353608-6a997f80-a49f-11e8-988e-b8c15898260d.gif)


[loaders_20_08_2018.zip](https://github.com/decred/dcrdesign/files/2303189/loaders_20_08_2018.zip)
[pendingTx_20_08_2018.zip](https://github.com/decred/dcrdesign/files/2303190/pendingTx_20_08_2018.zip)

3rd dot fixed in both packs. @linnutee
