### ISSUE TITLE
Stakey Sticker set for Telegram

### ISSUE THREAD

**Issue by marcelolustosa** [decred/dcrdesign#31]
Isaac, who manages our telegram channel, came to me and asked for Stakey images for Telegram. I know that platform has amazing support to transparent png's, so I decides to make an 'official' sticker set for it.

I think it worth some effort because the stickers can potentially be used in other CC-related groups. Also Telegram provides statistics about the stickers usage, which I'm going to track.

At first I'll recycle some old drawings as stickers; if that go well I can make new ones. Those could also work as printed custom cut stickers to compose our visual toolkit

**Comment by denyszayets** [comment]
I think it's a great idea. Especially because you've been working on Stakey for so long. Looking forward to see some of your ideas!

**Comment by marcelolustosa** [comment]
There's the old Stakeys turned to TG stickers:
![believe](https://user-images.githubusercontent.com/39598223/43799817-f01509f8-9a64-11e8-87a0-a44ede669607.png)
![bowie](https://user-images.githubusercontent.com/39598223/43799818-f036df1a-9a64-11e8-9131-4c6c66b8fc3b.png)
![bruce](https://user-images.githubusercontent.com/39598223/43799819-f0bd9c12-9a64-11e8-9957-bb3b2ff5f128.png)
![cow](https://user-images.githubusercontent.com/39598223/43799820-f0f8c850-9a64-11e8-9161-46d53d8f65aa.png)
![crocodile](https://user-images.githubusercontent.com/39598223/43799822-f11cc52a-9a64-11e8-8250-9472a83ab4f1.png)
![deal](https://user-images.githubusercontent.com/39598223/43799823-f13fe604-9a64-11e8-8800-05a08e64eb83.png)
![dyor](https://user-images.githubusercontent.com/39598223/43799824-f15e711e-9a64-11e8-87ac-b9d34ad7c109.png)
![gangnam](https://user-images.githubusercontent.com/39598223/43799825-f18161ba-9a64-11e8-825d-a28364085625.png)
![japan](https://user-images.githubusercontent.com/39598223/43799826-f1a04a1c-9a64-11e8-9407-b9eca1c7ad7e.png)
![korea](https://user-images.githubusercontent.com/39598223/43799827-f1c121f6-9a64-11e8-892f-5cc7861fde1d.png)
![lightning](https://user-images.githubusercontent.com/39598223/43799828-f1e0056c-9a64-11e8-9998-99bc9d740995.png)
![miami](https://user-images.githubusercontent.com/39598223/43799831-f20483f6-9a64-11e8-9647-2143e791c74c.png)
![midnight](https://user-images.githubusercontent.com/39598223/43799832-f2263762-9a64-11e8-89b8-921f8b3a3451.png)
![shake](https://user-images.githubusercontent.com/39598223/43799834-f2475b9a-9a64-11e8-981e-d97a34167c61.png)
![texas](https://user-images.githubusercontent.com/39598223/43799835-f267b46c-9a64-11e8-83d2-9e102a6ac717.png)
![thumbs](https://user-images.githubusercontent.com/39598223/43799837-f286bfa6-9a64-11e8-894e-e0145d80cba4.png)
![tokey](https://user-images.githubusercontent.com/39598223/43799838-f2a2e8ac-9a64-11e8-992c-f779a911f78b.png)

**Comment by GaneshAdimalupu** [comment]
do you have the  figma page or svg files?
