### ISSUE TITLE
dcrdocs design improvements 

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#33]
@MariaPleshkova

https://github.com/decred/dcrdocs/issues
https://docs.decred.org
This is based on a material-design mkdocs theme https://squidfunk.github.io/mkdocs-material/getting-started/ 

Scope of this task is fine tuning the material-design theme on low level (css and content changes) to further align with Decreds visual identity. 

**Tasks:**
- Map out instances for fixes and styling refinements
- Create bite-sized issues to github for implementation
- Limited to a single or few related elements
- Describe the problem and the suggested solution
- If needed provide mockup with specs for solving

**Theme-related:**
- Primarily focus on typography colours and smaller details, adding up to the identity and providing a good visual experience, appropriate contrasts, alignments, etc
- Create templates for both screenshots and instructional schematics

**Content:**
- Add/create missing icons
- Create new screenshots and schematics based on templates

**Example implementation issues:**
https://github.com/decred/decrediton/issues/1423
https://github.com/decred/decrediton/issues/1424
https://github.com/decred/decrediton/issues/1422
https://github.com/decred/decrediton/issues/1413

**Comment by MariaPleshkova** [comment]
**Change Header1 font and color**
decred/dcrdocs#556

**Change Header 2 font and color**
decred/dcrdocs#557

**Change Header 3 font and color**
decred/dcrdocs#570

**Change Header 4 font and color**
decred/dcrdocs#571

**Change Header 5 font and color**
decred/dcrdocs#572

**Change Header 6 font and color**
decred/dcrdocs#573

**Change body text font and color**
decred/dcrdocs#558

**Change bold body text font and color**
decred/dcrdocs#559

**Change blue color and the font of anchor text**
decred/dcrdocs#560

**Change the color of icon set**
decred/dcrdocs#561

**Change code-writing font**
decred/dcrdocs#562

**Change gray colour of the boxes with code**
decred/dcrdocs#563

**Example of code-writing (single word) when it’s in a gray rectangle**
decred/dcrdocs#564

**Change the size of the text in "Critical info", "Important info", etc. sections**
decred/dcrdocs#565

**Change the colour of gray elements (vertical line + text)**
decred/dcrdocs#566

**Add a vertical line next to the name of OS's and change the colour to green**
decred/dcrdocs#567

**Change the style of tables**
decred/dcrdocs#568

**Change the screenshot of dropdown list**
decred/dcrdocs#588

**Add a new diagram**
decred/dcrdocs#642
