### ISSUE TITLE
Twitter images: July - August

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#42]
Drop released ones here for archiving.

**Comment by 30000fps** [comment]
![dcr01_ticketsplitting](https://user-images.githubusercontent.com/15022929/45585724-9adf0d00-b8e9-11e8-96eb-34702e3a4855.gif)

**Comment by linnutee** [comment]
![dl3nkjyw0aae_ja jpg-large](https://user-images.githubusercontent.com/17774057/45597123-fbe11080-b9cf-11e8-9168-0b82ed17aac4.jpeg)
![dmb-cv9u0aabpwq png-large](https://user-images.githubusercontent.com/17774057/45597124-fbe11080-b9cf-11e8-8390-ea5877c54040.png)
![dkv1gfhuuaa23ca jpg-large](https://user-images.githubusercontent.com/17774057/45597126-fc79a700-b9cf-11e8-91f4-265059d6ac0f.jpeg)
![dj8gsmvx4ayvcxb jpg-large](https://user-images.githubusercontent.com/17774057/45597122-fbe11080-b9cf-11e8-8913-bfe9bd07bd13.jpeg)

**Comment by saender** [comment]
July/August journal release for Medium, Twitter post format:

![medium-july-journal-2018-twitter-format](https://user-images.githubusercontent.com/29069168/45686935-134a0600-bb56-11e8-83ff-40539865ca91.png)

![medium-august-journal-2018-twitter-format](https://user-images.githubusercontent.com/29069168/45686934-12b16f80-bb56-11e8-8de8-58a6f3cda677.png)

**Comment by marcelolustosa** [comment]
Jul/Aug Integration graphics
![dcr_integration](https://user-images.githubusercontent.com/39598223/45694974-d884a580-bb36-11e8-955e-07b5a1e89af9.png)
![dcr_integration_kucoin](https://user-images.githubusercontent.com/39598223/45695001-e3d7d100-bb36-11e8-9c49-51f73d6389ae.png)

**Comment by marcelolustosa** [comment]
Blockchain Voice Conference
![dcr---conference-template](https://user-images.githubusercontent.com/39598223/45695286-7b3d2400-bb37-11e8-9718-5d23b421444f.png)
