### ISSUE TITLE
Notifications overhaul

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#43]
Currently Decrediton uses basic error and success messages and an undefined snackbar pattern for larger actions/events. Goal is to create a notifications baseplate, that houses all of the different notification types and builds foundation for further organising the notifications feed.

**M1:**
1. Notification messages baseplate template (3-5 concept examples).
2. Includes: Icon, textual content, additional content (transaction details or error log), close button
3. Consider optimal positioning (e.g. hovers somewhere in top/header area)
4. Consider scalability, accordingly to amount of content
5. Consider semantics making sense and having appropriate nuance and hierarchy. (E.g. Data copied to clipboard not as important as succesfully Buying Tickets)
6.  Minimal use of color; rather rely on icons (and icon color if sensible). This is to avoid logic conflicts such as positive negatives (e.g. succesfully removed xyz)

Current types and examples:
1. Actions and Events (regardless of user action)
- Republished unmined transactions to the decred network.
- New transaction received {tx details}
2. Success (currently any kind of succesful user action)
- Ticket buyer is now running.
- You bought 2 tickets.
- Ticket buyer is now stopped.
- Seed copied to clipboard!
- Successfully set vote choices.
- Successfully added stakepool {host}
- Successfully removed StakePool config
3. Failure (currently any kind of failure from user action)
- Error syncing SPV wallet: {originalError}
- Error trying to add custom stakepool: {originalError}
- Unspecified system errors {originalError}

All message strings reference: https://github.com/decred/decrediton/blob/master/app/reducers/snackbar.js#L52

**M2:**
- Further define the specific messages, content and functionale (specified icons, interpolations etc) and prepare for implementation.

[Decrediton - notifications preview.zip](https://github.com/decred/dcrdesign/files/2389445/Decrediton.-.notifications.preview.zip)
[decrediton - master - v016.xd.zip](https://github.com/decred/dcrdesign/files/2389446/decrediton.-.master.-.v016.xd.zip)

**Comment by MariaPleshkova** [comment]
Relevant issue in /decrediton: https://github.com/decred/decrediton/issues/1696

XD layouts: [Notifications.zip](https://github.com/decred/dcrdesign/files/2456295/Notifications.zip)
