### ISSUE TITLE
Search filters optimizations

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#46]
The search filters is getting an additional feature added, which is filtering by amount. As this view will likely get some more fundamental updates in the future, should aim to fit solution in the current context. At the moment there’s three filtering options – by address field and two context menus containing: sort by newest, oldest; display specific tx types. 

Ideally the amounts can be displayed with a single bar and an option to clear/reset it. I recon this can be fitted under the “sort by” context menu (first icon, containing newest/oldest atm) by making the dropdown slightly larger and giving it separation. 

<img width="887" alt="screen shot 2018-09-30 at 20 40 50" src="https://user-images.githubusercontent.com/17774057/46260662-a3dafb80-c4f1-11e8-99f4-a09c3c116922.png">
<img width="717" alt="screen shot 2018-09-30 at 20 33 38" src="https://user-images.githubusercontent.com/17774057/46260665-a8071900-c4f1-11e8-85f3-923645deeac3.png">

<img width="869" alt="screen shot 2018-09-30 at 20 46 48" src="https://user-images.githubusercontent.com/17774057/46260705-003e1b00-c4f2-11e8-9f25-f9f15c44d5c6.png">

**Comment by MariaPleshkova** [comment]
https://github.com/decred/decrediton/issues/1706

XD files: [Amount range.zip](https://github.com/decred/dcrdesign/files/2469266/Amount.range.zip)
