### ISSUE TITLE
Stakey's Know your ticket - ticket status explained

### ISSUE THREAD

**Issue by marcelolustosa** [decred/dcrdesign#51]
Been working on individual ticket illustrations for each ticket status; finally had some time to finish a first version for review.

Got the text out of dcrdocs, with just minor adjustments. Feedback is welcome!

**Comment by marcelolustosa** [comment]
![dcr_-_ticket_-_unmined](https://user-images.githubusercontent.com/39598223/47042511-d4fa3380-d161-11e8-9cd7-96a794e3986e.png)
![dcr_-_ticket_-_immature](https://user-images.githubusercontent.com/39598223/47042523-db88ab00-d161-11e8-9153-ec200a86ef01.png)
![dcr_-_ticket_-_live](https://user-images.githubusercontent.com/39598223/47042532-e2afb900-d161-11e8-8710-027a1a67af14.png)
![dcr_-_ticket_-_voted](https://user-images.githubusercontent.com/39598223/47042580-0115b480-d162-11e8-952e-dc07a47330c4.png)

**Comment by marcelolustosa** [comment]
![dcr_-_ticket_-_missed](https://user-images.githubusercontent.com/39598223/47042717-65387880-d162-11e8-8ac2-a833d1dd61e0.png)
![dcr_-_ticket_-_expired](https://user-images.githubusercontent.com/39598223/47042726-6bc6f000-d162-11e8-8b1c-6d18fa33ec02.png)
![dcr_-_ticket_-_revoked](https://user-images.githubusercontent.com/39598223/47042732-6f5a7700-d162-11e8-95c7-946cc339e0e6.png)

**Comment by denyszayets** [comment]
Great job! I'm going to include these in our workshop on tickets.

**Comment by denyszayets** [comment]
### **Live ticket**
Suggested: _After maturation period of 256 blocks, it becomes live, entering the ticket pool and become eligible for voting._

### **Voted ticket:**
Suggested: _After a ticket has voted, your funds (ticket price + subsidy) will enter immature status for another 256 blocks, after which they are released to your account._

### **Missed ticket:**
Suggested: _If this happens, you receive a refund on the original ticket price minus fees._

### **Expired ticket:**
Suggested: _You receive a refund on the original Ticket Price minus fees._

**Comment by denyszayets** [comment]
my fault, I kept Ticket Pool in lowercase.

**Comment by marcelolustosa** [comment]
![dcr_-_ticket_-_unmined](https://user-images.githubusercontent.com/39598223/47574976-4e8ae200-d917-11e8-9610-5d97aebd7323.png)
![dcr_-_ticket_-_immature](https://user-images.githubusercontent.com/39598223/47574984-5480c300-d917-11e8-90bb-30ce65e5ceb5.png)
![dcr_-_ticket_-_live](https://user-images.githubusercontent.com/39598223/47574989-5a76a400-d917-11e8-9acd-a5f7be316234.png)
![dcr_-_ticket_-_voted](https://user-images.githubusercontent.com/39598223/47574993-5d719480-d917-11e8-8588-aca53632f07d.png)
![dcr_-_ticket_-_missed](https://user-images.githubusercontent.com/39598223/47575003-62cedf00-d917-11e8-84bf-4b63f224cf5d.png)
![dcr_-_ticket_-_expired](https://user-images.githubusercontent.com/39598223/47575044-842fcb00-d917-11e8-841e-9ca63f5bab8d.png)
![dcr_-_ticket_-_revoked](https://user-images.githubusercontent.com/39598223/47575019-71b59180-d917-11e8-9089-2b9a941c73ee.png)

**Comment by MaiconJunge** [comment]
Translate to Portuguese, please!

**Comment by marcelolustosa** [comment]
@MaiconJunge We're working to add this to Decrediton tutorials with proper localized versions :)
