### ISSUE TITLE
Websummit Lisbon - Decred Presentational Twitter Graphics

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#52]
Twitter images for the event below:

Event information: https://websummit.com/ - Portugal, Lisbon, 6/11 - 8/11

"Marco will be speaking, I believe, 8/11 @ 14:15-14:35."

@marcelolustosa does this sound right up your street?

**Comment by marcelolustosa** [comment]
@kyleFirethought will do!

**Comment by marcelolustosa** [comment]
is there a title for the speech? here's a good example of what kind of info we need:
https://twitter.com/decredproject/status/1032334800416206848

**Comment by kyleFirethought** [comment]
![capture](https://user-images.githubusercontent.com/7825971/47226728-2819f380-d3b9-11e8-9bca-393642f0a276.PNG)
Dug out some details for you^

**Comment by marcelolustosa** [comment]
![dcr---conference-template](https://user-images.githubusercontent.com/39598223/47245504-f1030c80-d3cf-11e8-9053-c70ab4860bee.png)

**Comment by kyleFirethought** [comment]
@linnutee. Looks good, going to close this issue for the time being. Might be worth popping a copy in design for any other peer review.  Thanks, another thing off the list for Websummit.
