### ISSUE TITLE
Iconset for #decrediton-dev - navigation

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#55]
Variants in the necessary Decrediton colour schemes for integration into application UI.

**Comment by linnutee** [comment]
Let's break these items down between navigation and other instances. I'll start by providing the colour codes for navigation.

**Comment by kyleFirethought** [comment]
[nav.-.icons18.-.motion.-.pack.zip](https://github.com/decred/dcrdesign/files/2508531/nav.-.icons18.-.motion.-.pack.zip)

Followed advice, both gif and png, png still in both still and animated swatches.  there is also both open and looped versions for flexibility in the future. Be aware there might be a slight discrepancy between svg and png icons due to the way AE imports within Title Safe through Overlord,  I have added a correction, however, there might be a "twitch" as you've stated on slack between svg and png icons. 

Let me know how you get along with the above and I'll be happy to make changes. 

Changes:

There is an added card_loop.

Let me know what you'd like to do with tx animations as there is only a depressed tx icon available at present.

**Comment by kyleFirethought** [comment]
![lock_eye_loop_nav](https://user-images.githubusercontent.com/7825971/47398874-08bef580-d72e-11e8-8013-6f8a044a6c60.gif)
![lock_eye_open_nav](https://user-images.githubusercontent.com/7825971/47398875-08bef580-d72e-11e8-9396-b6454e470b26.gif)
![options_b_loop_nav](https://user-images.githubusercontent.com/7825971/47398876-08bef580-d72e-11e8-82cb-b7463a9cced5.gif)
![options_b_open_nav](https://user-images.githubusercontent.com/7825971/47398877-08bef580-d72e-11e8-8b4f-532058988aad.gif)
![overview_loop_nav](https://user-images.githubusercontent.com/7825971/47398878-09578c00-d72e-11e8-8d0a-da61681f2848.gif)
![overview_open_nav](https://user-images.githubusercontent.com/7825971/47398879-09578c00-d72e-11e8-9afa-3097db56096b.gif)
![ticket_live_loop_90_degrees_nav](https://user-images.githubusercontent.com/7825971/47398880-09578c00-d72e-11e8-88c2-cfcd8d7fb55f.gif)
![ticket_live_open_90_degrees_nav](https://user-images.githubusercontent.com/7825971/47398881-09578c00-d72e-11e8-9353-2b7f0e147843.gif)
![card_loop_nav](https://user-images.githubusercontent.com/7825971/47398882-09578c00-d72e-11e8-8425-7df136fdb8d9.gif)
![card_open_nav](https://user-images.githubusercontent.com/7825971/47398883-09f02280-d72e-11e8-9861-c84beac31d72.gif)
![eye_open_nav](https://user-images.githubusercontent.com/7825971/47398884-09f02280-d72e-11e8-8049-75096cd89a68.gif)
![governance_opinions_loop_nav](https://user-images.githubusercontent.com/7825971/47398885-09f02280-d72e-11e8-9fe3-8e042850d941.gif)
![governance_opinions_open_nav](https://user-images.githubusercontent.com/7825971/47398886-09f02280-d72e-11e8-97c5-ef5dc8f0912a.gif)
![help_loop_nav](https://user-images.githubusercontent.com/7825971/47398887-09f02280-d72e-11e8-9b8d-f27fde76548e.gif)
![help_open_nav](https://user-images.githubusercontent.com/7825971/47398889-09f02280-d72e-11e8-9c4e-d9f9edd9d2ce.gif)

**Comment by kyleFirethought** [comment]
![lock_eye_loop_nav](https://user-images.githubusercontent.com/7825971/47399198-5ab44b00-d72f-11e8-9e25-73a830d4216d.gif)
![lock_eye_open_nav](https://user-images.githubusercontent.com/7825971/47399200-5ab44b00-d72f-11e8-9163-721f3e250b21.gif)
![options_b_loop_nav](https://user-images.githubusercontent.com/7825971/47399201-5ab44b00-d72f-11e8-8794-2017b1cc6b90.gif)
![options_b_open_nav](https://user-images.githubusercontent.com/7825971/47399202-5ab44b00-d72f-11e8-8a51-eeb6f2ba6fd5.gif)
![overview_loop_nav](https://user-images.githubusercontent.com/7825971/47399203-5ab44b00-d72f-11e8-95aa-3404bc719979.gif)
![overview_open_nav](https://user-images.githubusercontent.com/7825971/47399205-5b4ce180-d72f-11e8-80a4-b9328ca285d2.gif)
![ticket_live_loop_90_degrees_nav](https://user-images.githubusercontent.com/7825971/47399206-5b4ce180-d72f-11e8-997d-543f3746de10.gif)
![ticket_live_open_90_degrees_nav](https://user-images.githubusercontent.com/7825971/47399207-5b4ce180-d72f-11e8-942a-889af4a2342b.gif)
![transaction_depress_inv_nav](https://user-images.githubusercontent.com/7825971/47399208-5b4ce180-d72f-11e8-95a4-2f32d70c2a5e.gif)
![transaction_depress_inv_reverse_nav](https://user-images.githubusercontent.com/7825971/47399209-5b4ce180-d72f-11e8-936d-1378b6ea3ac0.gif)
![transaction_open_inv_nav](https://user-images.githubusercontent.com/7825971/47399210-5be57800-d72f-11e8-816a-dc87c0dbc788.gif)
![card_loop_nav](https://user-images.githubusercontent.com/7825971/47399211-5be57800-d72f-11e8-81f4-77ec834bc049.gif)
![card_open_nav](https://user-images.githubusercontent.com/7825971/47399213-5be57800-d72f-11e8-9728-83058ebc9d7a.gif)
![eye_open_nav](https://user-images.githubusercontent.com/7825971/47399214-5be57800-d72f-11e8-9b51-280505497e35.gif)
![governance_opinions_loop_nav](https://user-images.githubusercontent.com/7825971/47399215-5be57800-d72f-11e8-9e0b-1bc1231069ae.gif)
![governance_opinions_open_nav](https://user-images.githubusercontent.com/7825971/47399216-5be57800-d72f-11e8-9f13-f4cb0c953b9b.gif)
![help_loop_nav](https://user-images.githubusercontent.com/7825971/47399217-5c7e0e80-d72f-11e8-8374-40d196a2fc68.gif)
![help_open_nav](https://user-images.githubusercontent.com/7825971/47399218-5c7e0e80-d72f-11e8-9da3-5010291b761f.gif)

**Comment by linnutee** [comment]
Indeed, the tx icon can be a loop. 

Accounts one is alright animation wise, but does stand out much due to flipping in z. Can maybe consider another metaphor for this also, perhaps something similar to the ticket or maybe transition within the card that somehow references to a DCR address? 

Nitpicking around this as it will be a noticeable change of the metaphors. As you know we have a wallet for both wallets and accounts right now. That's a problem. The credit card was the most relevant one me and Kärt came up with so far. I'll share also a few other iterations of it, maybe there's some inspiration found to bolster its meaning through animation better. Reference to DCR addresses starting with D… is one that can be helpful from onboarding perspective. 

Also i'll mention that the png renders should be done at either @2x or @3x size, they'll eventually be downsized to 20px but this will make sure everything is crisp on retina screens. 

<img width="1486" alt="screen shot 2018-10-24 at 14 23 36" src="https://user-images.githubusercontent.com/17774057/47427250-7142bc80-d798-11e8-8de7-b6ad1cfa30cc.png">

[dcr - icons - account wip.zip](https://github.com/decred/dcrdesign/files/2510301/dcr.-.icons.-.account.wip.zip)

**Comment by kyleFirethought** [comment]
These other icons look so much easier to work with (both practically and from a narrative perspective). Will make the amendments above towards the end of the week. 

Thanks for the guidance re: formatting will get these packaged up to that spec^

**Comment by kyleFirethought** [comment]
![card_loop_var2](https://user-images.githubusercontent.com/7825971/47608068-80d43680-da20-11e8-9c92-9e2cdf12d712.gif)
![card_loop_var3](https://user-images.githubusercontent.com/7825971/47608069-816ccd00-da20-11e8-8ab3-dfda1a7178d5.gif)
![card_loop_var4](https://user-images.githubusercontent.com/7825971/47608070-816ccd00-da20-11e8-88b1-cf156a92b7c4.gif)
![card_open_var2](https://user-images.githubusercontent.com/7825971/47608071-816ccd00-da20-11e8-85a3-e865f70c6f3d.gif)
![card_open_var3](https://user-images.githubusercontent.com/7825971/47608072-816ccd00-da20-11e8-8125-1009ce66976c.gif)
![card_open_var4](https://user-images.githubusercontent.com/7825971/47608073-82056380-da20-11e8-82c1-6092a2f1db6d.gif)

**Comment by kyleFirethought** [comment]
card_open
![card_open_var5](https://user-images.githubusercontent.com/7825971/47682748-4e177300-dbc5-11e8-9fcc-302b1d9a9a6a.gif)

**Comment by kyleFirethought** [comment]
card_loop
![card_loop_var5](https://user-images.githubusercontent.com/7825971/47683859-cc294900-dbc8-11e8-886e-4863372343ae.gif)

**Comment by kyleFirethought** [comment]
Felt that above was more relevant than a caterpillar style "pending" motion as ultimately each account (box) is held under an extended public key (the single box). 

Does this make sense? @linnutee 

Will await the issue to be closed then package up the updated card animation.

**Comment by linnutee** [comment]
Included the latest version files. 

[decrediton - nav icons update - 291018.zip](https://github.com/decred/dcrdesign/files/2529504/decrediton.-.nav.icons.update.-.291018.zip)
