### ISSUE TITLE
Package all icons into master.-.iconset18.-.motion.-.pack

### ISSUE THREAD

**Issue by kyleFirethought** [decred/dcrdesign#56]
Package all icons including:

- [x] iconset18.-.base
- [x] nav.-.iconset18
- [x] loaders.-.iconset18
- [x] tx.-.iconset18
- [x] tickets.-.iconset18
- [x] roadmap18.-.iconset18
- [x] misc.-.iconset18

into a single archive for distribution.

**Comment by linnutee** [comment]
Preview: https://xd.adobe.com/view/248b42e5-5dd2-421e-74c5-71b13f399e11-52ba/
Specs: https://xd.adobe.com/spec/a0337ac4-8c31-4be1-4a87-4babfc87f845-d602/

[decrediton - ui v016 - nav icons update.zip](https://github.com/decred/dcrdesign/files/2506298/decrediton.-.ui.v016.-.nav.icons.update.zip)

**Comment by kyleFirethought** [comment]
Merge new icons into pack
