### ISSUE TITLE
Twitter images Oct 2018

### ISSUE THREAD

**Issue by marcelolustosa** [decred/dcrdesign#57]

**Comment by marcelolustosa** [comment]
![dcr_int_delta](https://user-images.githubusercontent.com/39598223/47313067-5b0bf380-d614-11e8-872d-663fa90fdfac.png)
![dcr_int_lrs](https://user-images.githubusercontent.com/39598223/47313074-5e06e400-d614-11e8-902e-078ccab88028.png)

**Comment by 30000fps** [comment]
![politeia_announce1](https://user-images.githubusercontent.com/15022929/47359811-f1502000-d6cd-11e8-985d-210a631d8c97.gif)
![politeia_announce2](https://user-images.githubusercontent.com/15022929/47359812-f1e8b680-d6cd-11e8-9db7-9f9f1622cb15.gif)

**Comment by linnutee** [comment]
![dcr - twitter - dcr summit - 2048px](https://user-images.githubusercontent.com/17774057/47377880-232daa80-d6ff-11e8-99cd-7525e9c57f09.png)
![dcr - twitter - texas conf - join me - 2048px](https://user-images.githubusercontent.com/17774057/47377870-21fc7d80-d6ff-11e8-81e3-7e9208f61a7b.png)
![dcr - twitter - scott dex - 2048px](https://user-images.githubusercontent.com/17774057/47377871-21fc7d80-d6ff-11e8-9859-9d08dce0798c.png)
![dcr - twitter - smaller talks - 2048px](https://user-images.githubusercontent.com/17774057/47377872-21fc7d80-d6ff-11e8-8b23-3f92a23bb6e9.png)
![dcr - twitter - luke pi architecture - 2048px](https://user-images.githubusercontent.com/17774057/47377874-21fc7d80-d6ff-11e8-90e4-55939d693378.png)
![dcr - twitter - marco governance - 2048px](https://user-images.githubusercontent.com/17774057/47377875-22951400-d6ff-11e8-8d5a-d2e946e66146.png)
![dcr - twitter - chapjc dcrdata - 2048px](https://user-images.githubusercontent.com/17774057/47377881-232daa80-d6ff-11e8-8635-4c03345af248.png)
![dcr - twitter - dz staking - 2048px](https://user-images.githubusercontent.com/17774057/47377876-22951400-d6ff-11e8-903f-3e0d85cb3707.png)
![dcr - twitter - joshua - 2048px](https://user-images.githubusercontent.com/17774057/47377877-22951400-d6ff-11e8-904b-57df7db82f67.png)
![dcr - twitter - joshua opt 2 - 2048px](https://user-images.githubusercontent.com/17774057/47377878-22951400-d6ff-11e8-826e-826c361c31d0.png)

Hackathon w/ @30000fps 
![decred - hackathon - 2048px](https://user-images.githubusercontent.com/17774057/47377882-232daa80-d6ff-11e8-885b-3664c4d4ee8a.png)
![decred - hackathon - twitter - 512px](https://user-images.githubusercontent.com/17774057/47377883-232daa80-d6ff-11e8-8835-a76397e0caac.gif)

**Comment by koosake** [comment]
![babystuff-01](https://user-images.githubusercontent.com/39430283/47913062-5ad8e700-dea3-11e8-9cb2-e7fabd93b5e5.png)
