### ISSUE TITLE
Roadmap Subpage

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#6]
- [x] Structural design
- [x] Visual design
- [x] New icons/symbols
- [x] Front-end implementation

**Comment by linnutee** [comment]
[dcrweb - roadmap - symbols 220518.zip](https://github.com/decred/dcrdesign/files/2031285/dcrweb.-.roadmap.-.symbols.220518.zip)

**Comment by denyszayets** [comment]
great work. Thanks for sharing
