### ISSUE TITLE
Copywriting request: Update/refine print handout content

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#60]
Currently there are three types of different handouts. Listed below w/ brief descriptions.

Ideally a single writer should take the lead on finalising the content and keeping up a consistent and well defined style. In case of bigger changes or additional asset requests, please keep in mind the print media size restrictions, what's suitable for what format, etc. 

**Small cards (A5 double sided):**
- Pre-event handoff (generic messaging + event details) 
- DCR Generic 
- Pi Generic
- DCR developers (suggest contributing) 
- DCR features

**Trifold fliers (A4 trifold):**
- Basic (oriented towards those with basic understanding of crypto space) 
- Devs (oriented towards devs or those with bit deeper understanding of crypto space) 

**Booklet (5.5 x 8.5 in / 16 pages):** 
- Intro, basics 
- Mission / fundamentals
- Features (generic)
- Atomic Swaps highlight
- LN highlight
- Pi highlight
- Pi use cases
- Dev highlight

[DCR - handouts - previews.zip](https://github.com/decred/dcrdesign/files/2516213/DCR.-.handouts.-.previews.zip)

**Comment by RichardRed0x** [comment]
How should the copywriter work on the copy and share that work? What format is the text stored in to generate the pdfs?

**Comment by linnutee** [comment]
As long as the final copy can be provided and not edited within the designed layout afterwards, the writing/editing process is really up to the copywriter to propose. Should be kept around gh and follow some basic standards to version control. Once the final version is delivered, the process around doing proof-reading for the designed version can be discussed over briefly. Ideal option would be using something like InCopy to really streamline the work, but I know this may be a lot to ask if not working with it by default.  

Otherwise the delivered text can be either markdown or rtf that highlight basic stylings such bolds, hyperlinks and such.

**Comment by Dustorf** [comment]
I think it only makes sense to maintain the two A4's and the booklet-per NABTC team feedback and others. Tom is working on the two A4's and will have something to me next week

**Comment by linnutee** [comment]
Alright, in case the content updates need new graphics, can refer to @koosake.
