### ISSUE TITLE
Decrediton: Add SPV enabling launch page 

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#61]
In reference to https://github.com/decred/decrediton/issues/1713

**Comment by MariaPleshkova** [comment]
As far as I understand, since it is for existing users only that it's better be a pop up, not a page, right?

**Comment by MariaPleshkova** [comment]
decred/decrediton#1755

XD file: [svp launcher.zip](https://github.com/decred/dcrdesign/files/2535686/svp.launcher.zip)
