### ISSUE TITLE
iOS App: Footer navigation options

### ISSUE THREAD

**Issue by denyszayets** [decred/dcrdesign#69]
I'd like to hear what you all think about this selection of navigation items available in iOS design.
By default we can have 5 items, unless we decide to allow users to swipe left and right on the menu to show full list:

**1. Overview**
**2. Transactions**
3. Tickets (sub)
**4. Governance**
**5. Accounts**
6. Security (sub)
**7. Settings**
8. Help (sub)

Once user selects Transactions for example, they will have the option to choose Send, Receive, history from top navigation bar.

Any suggestions on the best approach? Thanks

![4 0 home 2x](https://user-images.githubusercontent.com/33739891/47747032-ca5d9500-dc5d-11e8-9bd0-f140b4004a8f.png)

**Comment by justinsantoro** [comment]
Personally I think scrollable menus are annoying, but I suppose if you want to keep the same exact experience as in Decrediton it would be best. 

If you were to keep just 5, where would the rest go? I assume `Tickets` would be under `Governance` but what about the other two? `Security` under `Accounts`? and then `Help`....under settings? I think with only 5 `Help` would be the hardest to find, which may be counter-intuitive.

**Comment by raedah** [comment]
Agree on the scroll being annoying. There are currently no plans to allow staking in the mobile apps. We do not want to encouraging users to store large amounts of DCR on relatively insecure mobile devices.

**Comment by denyszayets** [comment]
**Agree.** In my opinion mobile app should be a Light Version of Decrediton. Send, Receive, View history.

**Comment by denyszayets** [comment]
this will get addressed later. Closing for now.
