### ISSUE TITLE
Decred logo Icon occupies too much clear space.

### ISSUE THREAD

**Issue by dmigwi** [decred/dcrdesign#70]
![screenshot from 2018-10-30 22-38-12](https://user-images.githubusercontent.com/22055953/47745851-ab7af500-dc95-11e8-98b5-48de3a976b1b.png)

The decred logo Icons as shown above occupy's too much clear space almost half of the Icon, this makes it hard to position it properly in the limited real estate that is available on the title bar in dcrdata.

Help in reducing the clear space so that the visible colors can occupy at least 90% of the space.

**Comment by justinsantoro** [comment]
[transparent_background_primary_nospace.zip](https://github.com/decred/dcrdesign/files/2531549/transparent_background_primary_nospace.zip)
here are all of the primary variants with the transparent space removed.

**Comment by dmigwi** [comment]
@gozart1  and @chappjc This images will fit better as the dcrdata logo versions as they have less clear space.

**Comment by chappjc** [comment]
Nice.  Thanks for following up @dmigwi.

**Comment by linnutee** [comment]
Keep in mind the some minimal spacing should be always left around the logo. The default spacing there is more generous due to it being often not kept in mind.
