### ISSUE TITLE
First run explainer for mobile users

### ISSUE THREAD

**Issue by raedah** [decred/dcrdesign#71]
Had this design idea so posting here instead of the mobile engineering repos.
Create a short intro guide about Decred that is displayed on the first run for mobile users to step through to  learn more, or easily bypass. Could talk about Decred in general or give some tips on how to use the mobile wallets. Mostly to provide a quaint welcoming feel when getting started.

**Comment by denyszayets** [comment]
@raedah I think this is a good idea. I can see a 3-5 on-boarding slides be very useful on first launch of the app. @kyleFirethought did some great work on decrediton, maybe he can help us with some animations for iOS/Android. I can then resize them to different screens.

**Comment by kyleFirethought** [comment]
Yeah, this all seems realistic; what spec would you need these pieces to be?

(There was an ambition early on to utilise assets from Decrediton's onboarding, this is still a possibility.)

**Comment by kyleFirethought** [comment]
Any further input here? Off to 🇵🇱 next week so quite keen to deliver deliverables or at least know what needs to be prepared on my arrival back? 👍

**Comment by kyleFirethought** [comment]
Closed due to inactivity^
