### ISSUE TITLE
Update reddit header 

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#73]
Since the header area takes up quite a lot of real-estate and attention, overall a more compact header version is preferred similar to http://reddit.com/r/monero/. Seems to work better in both light and dark mode and keeps attention on the content. 

Since the header isn't used to communicate anything actively, recommend the default state to be changed to smaller header with DCR logo in the left side and blue background. `#2970FF`

Anyone with admin access should be able to do this.

**Comment by siennet** [comment]
I'm going to tackle this issue.

**Comment by siennet** [comment]
![8cfa6729-d7f9-4875-9ffb-c532bdb6dd0e](https://user-images.githubusercontent.com/39701183/47963972-5aeef900-e001-11e8-84f3-29a130d745a8.png)
![4787cded-4ba1-4cbc-98d0-fe11cfa5d616](https://user-images.githubusercontent.com/39701183/47963973-5c202600-e001-11e8-80ee-d8deb6846482.png)
![feb10705-88d6-4fb6-926e-05ae69986bd1](https://user-images.githubusercontent.com/39701183/47963974-5cb8bc80-e001-11e8-9e3f-49025f3391d9.png)

These are the different ideas, which is most preferred?

**Comment by linnutee** [comment]
I assume this needs to be done within the reddit admin panel or through css, rather than making a new image. /r/monero doesn't display any header image in the source. 

Regarding the given example, none of these are valid for use: as the lock-up has messed with, color codes are wrong and the pos/neg versions are misused. Please exercise responsibility when working with DCR identity, as all these given edits are clearly described in the guidelines as bad practices.
