### ISSUE TITLE
Decred - Social media presence update - avatars, icons, banners, mastheads

### ISSUE THREAD

**Issue by saender** [decred/dcrdesign#78]
Regarding the identity overhaul, this is the package what went to use in social media.

Preview:
<img width="691" alt="preview" src="https://user-images.githubusercontent.com/29069168/48091402-47ff4300-e212-11e8-897e-e43ffc42323b.png">

Package:
[Decred - Social media - Avatar, icon, banner, masthead.zip](https://github.com/decred/dcrdesign/files/2554922/Decred.-.Social.media.avatar.icon.banner.masthead.update.package.zip)

**Comment by linnutee** [comment]
Referring this one also: 
https://github.com/decred/dcrdesign/issues/44
