### ISSUE TITLE
Treasury Icon

### ISSUE THREAD

**Issue by justinsantoro** [decred/dcrdesign#87]
I am in need of an icon to represent the Treasury. @linnutee and I spoke briefly on 12/5 and it was decided to take the safe vault symbol and make it into an icon as well. This is the final piece needed for the new "How Decred is Unique" video.

**Comment by linnutee** [comment]
@justinsantoro sharing the latest icon package with a safe vault included (110).
[dcr - icons - 191218.ai.zip](https://github.com/decred/dcrdesign/files/2699699/dcr.-.icons.-.191218.ai.zip)

**Comment by justinsantoro** [comment]
perfect. thank you!

**Comment by kyleFirethought** [comment]
![balance_loop](https://user-images.githubusercontent.com/7825971/50575781-6fcaeb80-0dfc-11e9-9d23-821b48718e31.gif)
![balance_open](https://user-images.githubusercontent.com/7825971/50575782-70638200-0dfc-11e9-80a9-43f5c6dfba87.gif)
![treasury_loop](https://user-images.githubusercontent.com/7825971/50575784-75283600-0dfc-11e9-97a2-fa1252233856.gif)
![treasury_open](https://user-images.githubusercontent.com/7825971/50575801-d5b77300-0dfc-11e9-9ea6-15876bbb0966.gif)
