### ISSUE TITLE
Onboarding slides

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#9]
- [x] Concept design
- [x] Storyboards
- [x] Illustrations
- [x] MD: Slide 1 
- [x] MD: Slide 2
- [x] MD: Slide 3
- [x] MD: Slide 4
- [x] Final Renders
- [x] Copywriting updates

**Comment by Firethought** [comment]
awaiting review of s3 visual elements & MD. https://decred.slack.com/files/U60H90MS4/FASQUH5PW/scene_3_not_signed.mp4
please note: hand elements to be tidied.

**Comment by Firethought** [comment]
awaiting review of updated s3 visual elements & MD. 
https://decred.slack.com/files/U60H90MS4/FAX2002BC/scene_3_not_signed.mp4

**Comment by Firethought** [comment]
awaiting review of updated s3 visual elements & MD.
https://decred.slack.com/files/U60H90MS4/FAX0LM49X/scene_3_not_signed.mp4
updated ending^

**Comment by denyszayets** [comment]
can't open the link
![screen shot on 2018-05-28 at 22_07_16](https://user-images.githubusercontent.com/33739891/40634549-8f78c180-62c3-11e8-9386-b6c5bf1cd7ea.png)

**Comment by Firethought** [comment]
awaiting review of updated s3 visual elements & MD.
https://decred.slack.com/files/U60H90MS4/FAYUUCGQ7/scene_3_not_signed.mp4
scale and recoil^

**Comment by Firethought** [comment]
s4 scenario base rigs complete (pending review).
background elements (to be discussed).
https://decred.slack.com/files/U60H90MS4/FAXUUJY8Z/warning.gif
https://decred.slack.com/files/U60H90MS4/FAY70E6MP/paper.gif
https://decred.slack.com/files/U60H90MS4/FAYT3HMGS/usb.gif
https://decred.slack.com/files/U60H90MS4/FAYSNJBR9/figure.gif

**Comment by linnutee** [comment]
Wrapping this up: 
Preview: https://xd.adobe.com/view/e93def3b-fb95-4b67-42b2-963ccd7db58c-9f0c/
Specs: https://xd.adobe.com/spec/200f3ec0-0db7-461e-5135-2622568d0565-563e/
Animation mp4's: https://drive.google.com/drive/folders/18lHNfTnKJbSfBVzKx0X127fU_103JKpb?usp=sharing

Posted for implementation in https://github.com/decred/decrediton/issues/1483

[decrediton - ui v015 - onboarding updates.zip](https://github.com/decred/dcrdesign/files/2119623/decrediton.-.ui.v015.-.onboarding.updates.zip)
