### ISSUE TITLE
Politeia Digest graphic

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdesign#90]
It has been suggested by a few people that pi digest could use its own graphic. That sounds good to me, but I don't have any strong opinions about what it should look like.

**Comment by linnutee** [comment]
Sander can produce the type overlay template, I recon this can be derived from dcr journal but with Pi symbol. 30kfps can think of a monthly/periodical visual of its own.

**Comment by saender** [comment]
Pi digest cover template for Medium, Twitter and Facebook.

Output preview:
<img width="597" alt="screen shot 2019-01-07 at 18 39 38" src="https://user-images.githubusercontent.com/29069168/50780532-da23d600-12ab-11e9-851a-6cc036c20ac7.png">

Template preview:
<img width="354" alt="screen shot 2019-01-07 at 18 40 44" src="https://user-images.githubusercontent.com/29069168/50780539-e14ae400-12ab-11e9-9a71-f9a6323f2a38.png">

Template file:
[Politeia - Medium, Twitter, Facebook "Politeia Digest" template.ai.zip](https://github.com/decred/dcrdesign/files/2733510/Politeia.-.Medium.Twitter.Facebook.Politeia.Digest.template.ai.zip)

**Comment by 30000fps** [comment]
1400 x 700 px
![politeia-digest_december2018_1400x700](https://user-images.githubusercontent.com/15022929/51254189-c6a9f680-19a0-11e9-8513-213af779d06e.png)
2048 x 1024 px
![politeia-digest_december2018_2048x1024](https://user-images.githubusercontent.com/15022929/51254197-cf023180-19a0-11e9-84fd-68922f7e4d86.png)
1200 x 628 px
![politeia-digest_december2018_1200x628](https://user-images.githubusercontent.com/15022929/51254205-d3c6e580-19a0-11e9-9971-a694ce2ef603.png)

**Comment by linnutee** [comment]
@RichardRed0x - closing this one. Feel free to open up new issue for January some time ahead of it getting released.
