### ISSUE TITLE
Decrediton: Adding another stakepool/success view

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdesign#99]
These stakepool configuration currently have no visual design to them. 

Current UI flow actually uses the same view twice. Will largely stick to that, with some minor changes.

- First instance, “Stakepool Succesfully Configured” view, where user adds a stakepool for the first time and receives a success confirmation. Only follow-up interaction is Continue, which directs to the Purchase tickets view.

- Second instance is when the user opens stakepool configuration view. In this instance, there can be one or more already configured stakepools, which need to be displayed there. Also there are three different interaction flows: delete stakepool (each), cancel (returns to purchase), add stakepool (directs to variant of add stakepool).

Workfiles: [decrediton - v017 - configured stakepools.xd.zip](https://github.com/decred/dcrdesign/files/2787449/decrediton.-.v017.-.configured.stakepools.xd.zip)

Sidenote: VSP terms not addressed yet, but as one go.

**Comment by MariaPleshkova** [comment]
decred/decrediton#2027

**XD file:** [Adding another stakepool - success view.zip](https://github.com/decred/dcrdesign/files/2856127/Adding.another.stakepool.-.success.view.zip)
